<script lang="ts">
  import "@inflatable-cookie/poodle-core/styles/waveform-display.css";
  import { createWaveformContext, waveformPointToSample, waveformTransition, waveformVisualState, type WaveformContext, type WaveformEffect, type WaveformPeakPyramid, type WaveformSelection } from "@inflatable-cookie/poodle-core";
  import WaveformVisual from "./audio/WaveformVisual.svelte";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";
  import type { ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";
  interface Props { size?: ControlSize | null; sizeRole?: SemanticControlSizeRole; density?: ControlDensity | null; pyramid?: WaveformPeakPyramid; visibleStart?: number; visibleEnd?: number; cursorSample?: number | null; selection?: WaveformSelection | null; columnCount?: number; disabled?: boolean; ariaLabel?: string | null; onCursorChange?: (sample: number) => void; onSelectionChange?: (selection: WaveformSelection | null) => void; onSelectionCommit?: (selection: WaveformSelection | null) => void; }
  let { size = null, sizeRole = "control", density = null, pyramid = { sampleCount: 0, levels: [] }, visibleStart = 0, visibleEnd = pyramid.sampleCount, cursorSample = $bindable(null), selection = $bindable(null), columnCount = 512, disabled = false, ariaLabel = "Waveform", onCursorChange, onSelectionChange, onSelectionCommit }: Props = $props();
  const uiPresentation = getUiPresentation(); const resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole)); const resolvedDensity = $derived(density ?? $uiPresentation.density);
  let root: HTMLDivElement; let machine = $state(createWaveformContext()); let activePointer: number | null = null;
  const context = $derived<WaveformContext>(createWaveformContext({ ...machine, pyramid, visibleStart, visibleEnd, cursorSample, selection, columnCount, disabled }));
  const visualState = $derived(waveformVisualState(context));
  const summary = $derived(`${ariaLabel ?? "Waveform"}, samples ${visibleStart} to ${visibleEnd}${cursorSample === null ? "" : `, cursor ${cursorSample}`}${selection === null ? "" : `, selection ${selection.start} to ${selection.end}`}`);
  function run(effects: WaveformEffect[]) { for (const effect of effects) { if (effect.type === "emitCursorChange") { cursorSample = effect.sample; onCursorChange?.(effect.sample); } else { selection = effect.selection; effect.type === "emitSelectionChange" ? onSelectionChange?.(effect.selection) : onSelectionCommit?.(effect.selection); } } }
  function send(event: Parameters<typeof waveformTransition>[1]) { const result = waveformTransition(context, event); machine = result.context; run(result.effects); }
  function sample(event: PointerEvent) { return waveformPointToSample({ x: event.clientX, y: event.clientY }, root.getBoundingClientRect(), visibleStart, visibleEnd); }
  function down(event: PointerEvent) { if (event.button !== 0 || disabled) return; event.preventDefault(); activePointer = event.pointerId; root.setPointerCapture(event.pointerId); send({ type: "SELECT_BEGIN", sample: sample(event) }); }
  function move(event: PointerEvent) { if (activePointer === event.pointerId) send({ type: "SELECT_MOVE", sample: sample(event) }); }
  function end(event: PointerEvent) { if (activePointer === event.pointerId) { activePointer = null; send({ type: "SELECT_END" }); } }
  function key(event: KeyboardEvent) { if (event.key === "ArrowLeft" || event.key === "ArrowRight") { event.preventDefault(); send({ type: "MOVE_CURSOR", delta: event.key === "ArrowRight" ? 1 : -1, extend: event.shiftKey }); } else if (event.key === "Home" || event.key === "End") { event.preventDefault(); send({ type: "BOUND_CURSOR", bound: event.key === "Home" ? "start" : "end", extend: event.shiftKey }); } else if (event.key === "Escape") { event.preventDefault(); send({ type: "CLEAR_SELECTION" }); } }
</script>
<div bind:this={root} class="poodle-waveform-display" role="slider" aria-label={summary} aria-disabled={disabled} aria-valuemin={visibleStart} aria-valuemax={Math.max(visibleEnd - 1, visibleStart)} aria-valuenow={cursorSample ?? visibleStart} aria-valuetext={summary} tabindex={disabled ? undefined : 0} data-scope="waveform-display" data-part="root" data-size={resolvedSize} data-density={resolvedDensity} onpointerdown={down} onpointermove={move} onpointerup={end} onpointercancel={end} onfocus={() => send({ type: "FOCUS", value: true })} onblur={() => send({ type: "FOCUS", value: false })} onkeydown={key}><WaveformVisual {visualState} /></div>
