//! pug-gpui-components — Real renderable GPUI components backed by Pug spec structs.
//!
//! Each component wraps a spec from `pug_gpui_primitives`, resolves tokens through
//! `GpuiThemeProvider`, and implements `IntoElement` to produce interactive gpui elements.

pub mod theme_ext;

mod action_discovery_panel;
mod accordion;
mod alert_dialog;
mod app_header;
mod breadcrumbs;
mod bulk_action_bar;
mod bx;
mod button;
mod calendar;
mod callout;
mod card;
mod checkbox;
mod code;
mod collapse_toggle;
mod collapsible;
mod color_picker;
mod combobox;
mod command_palette;
mod context_menu;
mod data_table;
mod date_picker;
mod date_range_picker;
mod date_time_picker;
mod date_time_range_picker;
mod detail_row;
mod detail_section;
mod detail_shell;
mod dialog;
mod dock_region;
mod drawer;
mod duration_input;
mod editable_label;
mod empty_state;
mod eyebrow;
mod field;
mod file_upload;
mod filter_toolbar;
mod form_actions;
mod grid;
mod hover_card;
mod icon;
pub mod icon_registry;
mod icon_button;
mod list_card;
mod media_preview;
mod media_thumbnail;
mod menu;
mod metric_tile;
mod menubar;
mod meter;
mod nav_card;
mod nav_card_grid;
mod navigation_menu;
mod number_entry;
mod order_by;
mod page_header;
mod pagination;
mod pagination_summary;
mod picker_shell;
mod pill;
mod pin_input;
mod popover;
mod progress;
mod radio_group;
mod range_calendar;
mod range_slider;
mod rating;
mod region;
mod relation_picker;
mod resize_handle;
mod scroll_shell;
mod search_field;
mod segmented_control;
mod select;
mod selection_summary;
mod separator;
mod skeleton;
mod slider;
mod spacer;
mod split_button;
mod split_view;
mod stack;
mod status_bar;
mod status_indicator;
mod surface;
mod switch;
mod tab_strip;
mod tabs;
mod table;
mod text_area;
mod toast_stack;
mod text_input;
mod time_ago;
mod time_field;
mod time_zone_select;
pub mod toggle;
mod toggle_group;
mod toolbar;
mod tooltip;
mod tri_state_switch;
mod zoned_date_time_picker;

pub use action_discovery_panel::PugActionDiscoveryPanel;
pub use accordion::PugAccordion;
pub use alert_dialog::PugAlertDialog;
pub use app_header::PugAppHeader;
pub use breadcrumbs::PugBreadcrumbs;
pub use bulk_action_bar::PugBulkActionBar;
pub use bx::PugBox;
pub use button::PugButton;
pub use calendar::PugCalendar;
pub use callout::PugCallout;
pub use card::PugCard;
pub use checkbox::PugCheckbox;
pub use code::PugCode;
pub use collapse_toggle::PugCollapseToggle;
pub use collapsible::PugCollapsible;
pub use color_picker::PugColorPicker;
pub use combobox::PugCombobox;
pub use command_palette::PugCommandPalette;
pub use context_menu::PugContextMenu;
pub use data_table::PugDataTable;
pub use date_picker::PugDatePicker;
pub use date_range_picker::PugDateRangePicker;
pub use date_time_picker::PugDateTimePicker;
pub use date_time_range_picker::PugDateTimeRangePicker;
pub use detail_row::PugDetailRow;
pub use detail_section::PugDetailSection;
pub use detail_shell::PugDetailShell;
pub use dialog::PugDialog;
pub use dock_region::PugDockRegion;
pub use drawer::PugDrawer;
pub use duration_input::PugDurationInput;
pub use editable_label::PugEditableLabel;
pub use empty_state::PugEmptyState;
pub use eyebrow::PugEyebrow;
pub use field::PugField;
pub use file_upload::PugFileUpload;
pub use filter_toolbar::PugFilterToolbar;
pub use form_actions::PugFormActions;
pub use grid::PugGrid;
pub use hover_card::PugHoverCard;
pub use icon::PugIcon;
pub use icon_button::PugIconButton;
pub use list_card::PugListCard;
pub use media_preview::PugMediaPreview;
pub use media_thumbnail::PugMediaThumbnail;
pub use menu::PugMenu;
pub use metric_tile::PugMetricTile;
pub use menubar::PugMenubar;
pub use meter::PugMeter;
pub use nav_card::PugNavCard;
pub use nav_card_grid::PugNavCardGrid;
pub use navigation_menu::PugNavigationMenu;
pub use number_entry::PugNumberEntry;
pub use order_by::PugOrderBy;
pub use page_header::PugPageHeader;
pub use pagination::PugPagination;
pub use pagination_summary::PugPaginationSummary;
pub use picker_shell::PugPickerShell;
pub use pill::PugPill;
pub use pin_input::PugPinInput;
pub use popover::PugPopover;
pub use progress::PugProgress;
pub use radio_group::PugRadioGroup;
pub use range_calendar::PugRangeCalendar;
pub use range_slider::PugRangeSlider;
pub use rating::PugRating;
pub use region::PugRegion;
pub use relation_picker::PugRelationPicker;
pub use resize_handle::PugResizeHandle;
pub use scroll_shell::PugScrollShell;
pub use search_field::PugSearchField;
pub use segmented_control::PugSegmentedControl;
pub use select::PugSelect;
pub use selection_summary::PugSelectionSummary;
pub use separator::PugSeparator;
pub use skeleton::PugSkeleton;
pub use slider::PugSlider;
pub use spacer::PugSpacer;
pub use split_button::PugSplitButton;
pub use split_view::PugSplitView;
pub use stack::PugStack;
pub use status_bar::PugStatusBar;
pub use status_indicator::PugStatusIndicator;
pub use surface::PugSurface;
pub use switch::PugSwitch;
pub use tab_strip::PugTabStrip;
pub use tabs::PugTabs;
pub use table::PugTable;
pub use text_area::PugTextArea;
pub use toast_stack::PugToastStack;
pub use text_input::PugTextInput;
pub use time_ago::PugTimeAgo;
pub use time_field::PugTimeField;
pub use time_zone_select::PugTimeZoneSelect;
pub use toggle::PugToggle;
pub use toggle_group::{PugToggleGroup, ToggleGroupItem};
pub use toolbar::PugToolbar;
pub use tooltip::PugTooltip;
pub use tri_state_switch::PugTriStateSwitch;
pub use zoned_date_time_picker::PugZonedDateTimePicker;
