//! pug-gpui-components — Real renderable GPUI components backed by Pug spec structs.
//!
//! Each component wraps a spec from `pug_gpui_primitives`, resolves tokens through
//! `GpuiThemeProvider`, and implements `IntoElement` to produce interactive gpui elements.

pub mod theme_ext;

mod action_discovery_panel;
mod accordion;
mod app_header;
mod badge;
mod banner;
mod bx;
mod button;
mod calendar;
mod call_out;
mod checkbox;
mod code;
mod collapsible;
mod color_picker;
mod command_palette;
mod command_palette_shell;
mod context_menu;
mod data_table;
mod date_picker;
mod date_range_picker;
mod date_time_picker;
mod date_time_range_picker;
mod detail_shell;
mod dialog;
mod dock_region;
mod drawer;
mod duration_input;
mod editable_label;
mod empty_state;
mod eyebrow;
mod field;
mod file_upload;
mod filter_toolbar;
mod form_actions;
mod form_shell;
mod grid;
mod grid_shell;
mod hover_card;
mod icon_button;
mod inline;
mod inline_remediation;
mod list_shell;
mod media_preview;
mod media_thumbnail;
mod menu;
mod menubar;
mod meter;
mod navigation_menu;
mod number_entry;
mod pagination_summary;
mod panel_header;
mod panel_surface;
mod panel_tabs;
mod picker_shell;
mod pill;
mod pin_input;
mod popover;
mod progress;
mod project_header;
mod radio_group;
mod range_calendar;
mod range_slider;
mod rating;
mod relation_picker;
mod remediation_banner;
mod scroll_shell;
mod search_field;
mod segmented_control;
mod select;
mod selection_summary;
mod separator;
mod shell_status_bar;
mod skeleton;
mod slider;
mod spacer;
mod split_button;
mod split_view;
mod stack;
mod status_indicator;
mod surface;
mod surface_tabs;
mod switch;
mod tab_strip;
mod tabs;
mod text_area;
mod text_input;
mod time_ago;
mod time_field;
mod time_zone_select;
pub mod toggle;
mod toggle_group;
mod toolbar;
mod tooltip;
mod tri_state_switch;
mod validation_summary;
mod workspace_shell;
mod zoned_date_time_picker;

pub use action_discovery_panel::PugActionDiscoveryPanel;
pub use accordion::PugAccordion;
pub use app_header::PugAppHeader;
pub use badge::PugBadge;
pub use banner::PugBanner;
pub use bx::PugBox;
pub use button::PugButton;
pub use calendar::PugCalendar;
pub use call_out::PugCallOut;
pub use checkbox::PugCheckbox;
pub use code::PugCode;
pub use collapsible::PugCollapsible;
pub use color_picker::PugColorPicker;
pub use command_palette::PugCommandPalette;
pub use command_palette_shell::PugCommandPaletteShell;
pub use context_menu::PugContextMenu;
pub use data_table::PugDataTable;
pub use date_picker::PugDatePicker;
pub use date_range_picker::PugDateRangePicker;
pub use date_time_picker::PugDateTimePicker;
pub use date_time_range_picker::PugDateTimeRangePicker;
pub use detail_shell::PugDetailShell;
pub use dialog::PugDialog;
pub use dock_region::PugDockRegion;
pub use drawer::PugDrawer;
pub use duration_input::PugDurationInput;
pub use editable_label::PugEditableLabel;
pub use empty_state::PugEmptyState;
pub use eyebrow::PugEyebrow;
pub use field::PugField;
pub use file_upload::PugFileUpload;
pub use filter_toolbar::PugFilterToolbar;
pub use form_actions::PugFormActions;
pub use form_shell::PugFormShell;
pub use grid::PugGrid;
pub use grid_shell::PugGridShell;
pub use hover_card::PugHoverCard;
pub use icon_button::PugIconButton;
pub use inline::PugInline;
pub use inline_remediation::PugInlineRemediation;
pub use list_shell::PugListShell;
pub use media_preview::PugMediaPreview;
pub use media_thumbnail::PugMediaThumbnail;
pub use menu::PugMenu;
pub use menubar::PugMenubar;
pub use meter::PugMeter;
pub use navigation_menu::PugNavigationMenu;
pub use number_entry::PugNumberEntry;
pub use pagination_summary::PugPaginationSummary;
pub use panel_header::PugPanelHeader;
pub use panel_surface::PugPanelSurface;
pub use panel_tabs::PugPanelTabs;
pub use picker_shell::PugPickerShell;
pub use pill::PugPill;
pub use pin_input::PugPinInput;
pub use popover::PugPopover;
pub use progress::PugProgress;
pub use project_header::PugProjectHeader;
pub use radio_group::PugRadioGroup;
pub use range_calendar::PugRangeCalendar;
pub use range_slider::PugRangeSlider;
pub use rating::PugRating;
pub use relation_picker::PugRelationPicker;
pub use remediation_banner::PugRemediationBanner;
pub use scroll_shell::PugScrollShell;
pub use search_field::PugSearchField;
pub use segmented_control::PugSegmentedControl;
pub use select::PugSelect;
pub use selection_summary::PugSelectionSummary;
pub use separator::PugSeparator;
pub use shell_status_bar::PugShellStatusBar;
pub use skeleton::PugSkeleton;
pub use slider::PugSlider;
pub use spacer::PugSpacer;
pub use split_button::PugSplitButton;
pub use split_view::PugSplitView;
pub use stack::PugStack;
pub use status_indicator::PugStatusIndicator;
pub use surface::PugSurface;
pub use surface_tabs::PugSurfaceTabs;
pub use switch::PugSwitch;
pub use tab_strip::PugTabStrip;
pub use tabs::PugTabs;
pub use text_area::PugTextArea;
pub use text_input::PugTextInput;
pub use time_ago::PugTimeAgo;
pub use time_field::PugTimeField;
pub use time_zone_select::PugTimeZoneSelect;
pub use toggle::PugToggle;
pub use toggle_group::{PugToggleGroup, ToggleGroupItem};
pub use toolbar::PugToolbar;
pub use tooltip::PugTooltip;
pub use tri_state_switch::PugTriStateSwitch;
pub use validation_summary::PugValidationSummary;
pub use workspace_shell::PugWorkspaceShell;
pub use zoned_date_time_picker::PugZonedDateTimePicker;
