//! pug-gpui-components — Real renderable GPUI components backed by Pug spec structs.
//!
//! Each component wraps a spec from `pug_gpui_primitives`, resolves tokens through
//! `GpuiThemeProvider`, and implements `IntoElement` to produce interactive gpui elements.

pub mod theme_ext;

mod accordion;
mod badge;
mod bx;
mod button;
mod calendar;
mod checkbox;
mod collapsible;
mod context_menu;
mod date_picker;
mod date_range_picker;
mod date_time_picker;
mod date_time_range_picker;
mod dialog;
mod drawer;
mod field;
mod form_actions;
mod grid;
mod icon_button;
mod menu;
mod menubar;
mod navigation_menu;
mod popover;
mod progress;
mod radio_group;
mod range_calendar;
mod scroll_shell;
mod search_field;
mod segmented_control;
mod select;
mod separator;
mod slider;
mod stack;
mod status_indicator;
mod surface;
mod switch;
mod tab_strip;
mod tabs;
mod text_area;
mod text_input;
mod time_field;
mod tooltip;

pub use accordion::PugAccordion;
pub use badge::PugBadge;
pub use bx::PugBox;
pub use button::PugButton;
pub use calendar::PugCalendar;
pub use checkbox::PugCheckbox;
pub use collapsible::PugCollapsible;
pub use context_menu::PugContextMenu;
pub use date_picker::PugDatePicker;
pub use date_range_picker::PugDateRangePicker;
pub use date_time_picker::PugDateTimePicker;
pub use date_time_range_picker::PugDateTimeRangePicker;
pub use dialog::PugDialog;
pub use drawer::PugDrawer;
pub use field::PugField;
pub use form_actions::PugFormActions;
pub use grid::PugGrid;
pub use icon_button::PugIconButton;
pub use menu::PugMenu;
pub use menubar::PugMenubar;
pub use navigation_menu::PugNavigationMenu;
pub use popover::PugPopover;
pub use progress::PugProgress;
pub use radio_group::PugRadioGroup;
pub use range_calendar::PugRangeCalendar;
pub use scroll_shell::PugScrollShell;
pub use search_field::PugSearchField;
pub use segmented_control::PugSegmentedControl;
pub use select::PugSelect;
pub use separator::PugSeparator;
pub use slider::PugSlider;
pub use stack::PugStack;
pub use status_indicator::PugStatusIndicator;
pub use surface::PugSurface;
pub use switch::PugSwitch;
pub use tab_strip::PugTabStrip;
pub use tabs::PugTabs;
pub use text_area::PugTextArea;
pub use text_input::PugTextInput;
pub use time_field::PugTimeField;
pub use tooltip::PugTooltip;
