// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

#[derive(Debug, Clone, Copy)]
pub struct DensityDefinition {
    pub name: &'static str,
    pub selector: &'static str,
    pub overrides: &'static [(&'static str, &'static str)],
}

#[derive(Debug, Clone, Copy)]
pub struct ControlSizeDefinition {
    pub name: &'static str,
    pub selector: &'static str,
    pub overrides: &'static [(&'static str, &'static str)],
}

pub const COMFORTABLE: DensityDefinition = DensityDefinition {
    name: "comfortable",
    selector: "[data-density=\"comfortable\"]",
    overrides: &[
    ("semantic.space.panel.x", "20px"),
    ("semantic.space.panel.y", "16px"),
    ("semantic.space.control.x", "16px"),
    ("semantic.space.control.y", "12px"),
    ("semantic.space.stack.md", "16px"),
    ("semantic.space.stack.lg", "24px"),
    ("semantic.size.control.height", "44px"),
    ("semantic.size.panel.header", "44px"),
    ],
};

pub const COMPACT: DensityDefinition = DensityDefinition {
    name: "compact",
    selector: "[data-density=\"compact\"]",
    overrides: &[
    ("semantic.space.panel.x", "12px"),
    ("semantic.space.panel.y", "8px"),
    ("semantic.space.control.x", "8px"),
    ("semantic.space.control.y", "4px"),
    ("semantic.space.stack.md", "8px"),
    ("semantic.space.stack.lg", "16px"),
    ("semantic.size.control.height", "28px"),
    ("semantic.size.panel.header", "36px"),
    ],
};

pub const CONTROL_SIZE_LG: ControlSizeDefinition = ControlSizeDefinition {
    name: "lg",
    selector: "[data-control-size=\"lg\"]",
    overrides: &[
    ("semantic.size.control.height", "44px"),
    ("semantic.size.control.minWidth", "112px"),
    ("semantic.size.icon.default", "20px"),
    ],
};

pub const CONTROL_SIZE_MD: ControlSizeDefinition = ControlSizeDefinition {
    name: "md",
    selector: "[data-control-size=\"md\"]",
    overrides: &[
    ("semantic.size.control.height", "36px"),
    ("semantic.size.control.minWidth", "96px"),
    ("semantic.size.icon.default", "16px"),
    ],
};

pub const CONTROL_SIZE_SM: ControlSizeDefinition = ControlSizeDefinition {
    name: "sm",
    selector: "[data-control-size=\"sm\"]",
    overrides: &[
    ("semantic.size.control.height", "28px"),
    ("semantic.size.control.minWidth", "84px"),
    ("semantic.size.icon.default", "12px"),
    ],
};
