// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

#[derive(Debug, Clone, Copy)]
pub struct DensityDefinition {
    pub name: &'static str,
    pub selector: &'static str,
    pub overrides: &'static [(&'static str, &'static str)],
}

#[derive(Debug, Clone, Copy)]
pub struct ControlSizeDefinition {
    pub name: &'static str,
    pub selector: &'static str,
    pub overrides: &'static [(&'static str, &'static str)],
}

pub const COMFORTABLE: DensityDefinition = DensityDefinition {
    name: "comfortable",
    selector: "[data-density=\"comfortable\"]",
    overrides: &[
    ("semantic.space.panel.x", "1.25rem"),
    ("semantic.space.panel.y", "1rem"),
    ("semantic.space.control.x", "1rem"),
    ("semantic.space.control.y", "0.75rem"),
    ("semantic.space.stack.md", "1rem"),
    ("semantic.space.stack.lg", "1.5rem"),
    ("semantic.size.control.height", "2.75rem"),
    ("semantic.size.panel.header", "2.75rem"),
    ],
};

pub const COMPACT: DensityDefinition = DensityDefinition {
    name: "compact",
    selector: "[data-density=\"compact\"]",
    overrides: &[
    ("semantic.space.panel.x", "0.75rem"),
    ("semantic.space.panel.y", "0.5rem"),
    ("semantic.space.control.x", "0.5rem"),
    ("semantic.space.control.y", "0.25rem"),
    ("semantic.space.stack.md", "0.5rem"),
    ("semantic.space.stack.lg", "1rem"),
    ("semantic.size.control.height", "1.75rem"),
    ("semantic.size.panel.header", "2.25rem"),
    ],
};

pub const DEFAULT: DensityDefinition = DensityDefinition {
    name: "default",
    selector: "[data-density=\"default\"]",
    overrides: &[
    ("semantic.space.panel.x", "1rem"),
    ("semantic.space.panel.y", "0.75rem"),
    ("semantic.space.control.x", "0.75rem"),
    ("semantic.space.control.y", "0.5rem"),
    ("semantic.space.stack.md", "0.75rem"),
    ("semantic.space.stack.lg", "1.25rem"),
    ("semantic.size.control.height", "2.25rem"),
    ("semantic.size.panel.header", "2.5rem"),
    ],
};

pub const CONTROL_SIZE_LG: ControlSizeDefinition = ControlSizeDefinition {
    name: "lg",
    selector: "[data-control-size=\"lg\"]",
    overrides: &[
    ("semantic.size.control.height", "2.75rem"),
    ("semantic.size.control.minWidth", "7rem"),
    ("semantic.size.icon.default", "1.25rem"),
    ],
};

pub const CONTROL_SIZE_MD: ControlSizeDefinition = ControlSizeDefinition {
    name: "md",
    selector: "[data-control-size=\"md\"]",
    overrides: &[
    ("semantic.size.control.height", "2.25rem"),
    ("semantic.size.control.minWidth", "6rem"),
    ("semantic.size.icon.default", "1rem"),
    ],
};

pub const CONTROL_SIZE_SM: ControlSizeDefinition = ControlSizeDefinition {
    name: "sm",
    selector: "[data-control-size=\"sm\"]",
    overrides: &[
    ("semantic.size.control.height", "1.75rem"),
    ("semantic.size.control.minWidth", "5.25rem"),
    ("semantic.size.icon.default", "0.75rem"),
    ],
};

pub const CONTROL_SIZE_XL: ControlSizeDefinition = ControlSizeDefinition {
    name: "xl",
    selector: "[data-control-size=\"xl\"]",
    overrides: &[
    ("semantic.size.control.height", "3.25rem"),
    ("semantic.size.control.minWidth", "8rem"),
    ("semantic.size.icon.default", "1.5rem"),
    ],
};

pub const CONTROL_SIZE_XS: ControlSizeDefinition = ControlSizeDefinition {
    name: "xs",
    selector: "[data-control-size=\"xs\"]",
    overrides: &[
    ("semantic.size.control.height", "1.5rem"),
    ("semantic.size.control.minWidth", "4.5rem"),
    ("semantic.size.icon.default", "0.625rem"),
    ],
};
