// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

pub const MANIFEST_NAME: &str = "@flint/tokens";
pub const MANIFEST_VERSION: &str = "0.0.0";
pub const CANONICAL_FORMAT: &str = "W3C DTCG 2025.10";
pub const ARTIFACT_BASELINE: &str = "Style Dictionary 4.x target shapes with bootstrap local emission script";

pub const ALIASES: &[(&str, &str)] = &[
    ("semantic.color.accent.base", "semantic.color.accent.base"),
    ("semantic.size.control.height", "semantic.size.control.height"),
];

pub const DEPRECATIONS: &[(&str, &str)] = &[
    ("semantic.color.border.default", "active"),
];
