// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

#[derive(Debug, Clone, Copy)]
pub struct ThemeDefinition {
    pub name: &'static str,
    pub selector: &'static str,
    pub overrides: &'static [(&'static str, &'static str)],
}

pub const DARK: ThemeDefinition = ThemeDefinition {
    name: "dark",
    selector: "[data-theme=\"dark\"]",
    overrides: &[
    ("color.background.canvas", "#0e1012"),
    ("color.background.surface", "#15181b"),
    ("color.background.panel", "#1b1f23"),
    ("color.background.elevated", "#20252a"),
    ("color.background.overlay", "rgba(8, 10, 13, 0.78)"),
    ("color.text.primary", "#eef2f6"),
    ("color.text.secondary", "#99a4b0"),
    ("color.text.inverse", "#161a1f"),
    ("color.border.subtle", "rgba(227, 232, 238, 0.12)"),
    ("color.border.default", "rgba(227, 232, 238, 0.22)"),
    ("color.border.strong", "rgba(227, 232, 238, 0.42)"),
    ("color.accent.base", "#f0b24d"),
    ("color.accent.hover", "#ffca73"),
    ("color.accent.focusRing", "#ffca73"),
    ("color.icon.primary", "#eef2f6"),
    ("color.icon.muted", "#99a4b0"),
    ],
};

pub const LIGHT: ThemeDefinition = ThemeDefinition {
    name: "light",
    selector: "[data-theme=\"light\"]",
    overrides: &[
    ("color.background.canvas", "#e7eef5"),
    ("color.background.surface", "#dbe5ef"),
    ("color.background.panel", "#f7fafd"),
    ("color.background.elevated", "#fcfdff"),
    ("color.text.primary", "#131a22"),
    ("color.text.secondary", "#314255"),
    ("color.border.subtle", "#c9d4e0"),
    ("color.border.default", "#75869b"),
    ("color.icon.primary", "#131a22"),
    ("color.icon.muted", "#314255"),
    ],
};

pub const LOOPHOLE_STUDIO: ThemeDefinition = ThemeDefinition {
    name: "loophole-studio",
    selector: "[data-theme=\"loophole-studio\"]",
    overrides: &[
    ("color.background.canvas", "#111111"),
    ("color.background.surface", "#181818"),
    ("color.background.panel", "#202020"),
    ("color.background.elevated", "#292929"),
    ("color.background.overlay", "rgba(8, 8, 8, 0.82)"),
    ("color.text.primary", "#efefef"),
    ("color.text.secondary", "#a6a6a6"),
    ("color.text.inverse", "#151515"),
    ("color.border.subtle", "rgba(198, 198, 198, 0.14)"),
    ("color.border.default", "rgba(198, 198, 198, 0.24)"),
    ("color.border.strong", "rgba(198, 198, 198, 0.42)"),
    ("color.accent.base", "#97d14d"),
    ("color.accent.hover", "#b5e36f"),
    ("color.accent.focusRing", "#b5e36f"),
    ("color.status.success", "#97d14d"),
    ("color.status.warning", "#f0ba55"),
    ("color.status.danger", "#ef7c72"),
    ("color.status.info", "#6ea9d4"),
    ("color.icon.primary", "#efefef"),
    ("color.icon.muted", "#a6a6a6"),
    ],
};
