// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

#[derive(Debug, Clone, Copy)]
pub struct ThemeDefinition {
    pub name: &'static str,
    pub selector: &'static str,
    pub overrides: &'static [(&'static str, &'static str)],
}

pub const DARK: ThemeDefinition = ThemeDefinition {
    name: "dark",
    selector: "[data-theme=\"dark\"]",
    overrides: &[
    ("semantic.color.background.canvas", "#0b0f14"),
    ("semantic.color.background.surface", "#11161d"),
    ("semantic.color.background.panel", "#1a212c"),
    ("semantic.color.background.elevated", "#1a212c"),
    ("semantic.color.background.overlay", "rgba(11, 15, 20, 0.76)"),
    ("semantic.color.text.primary", "#e7eef5"),
    ("semantic.color.text.secondary", "#75869b"),
    ("semantic.color.text.inverse", "#131a22"),
    ("semantic.color.border.subtle", "rgba(215, 221, 230, 0.12)"),
    ("semantic.color.border.default", "rgba(215, 221, 230, 0.24)"),
    ("semantic.color.border.strong", "rgba(215, 221, 230, 0.48)"),
    ("semantic.color.accent.base", "#57a7ff"),
    ("semantic.color.accent.hover", "#2d86f3"),
    ("semantic.color.accent.focusRing", "#57a7ff"),
    ("semantic.color.icon.primary", "#e7eef5"),
    ("semantic.color.icon.muted", "#75869b"),
    ],
};

pub const LIGHT: ThemeDefinition = ThemeDefinition {
    name: "light",
    selector: "[data-theme=\"light\"]",
    overrides: &[
    ("semantic.color.background.canvas", "#e7eef5"),
    ("semantic.color.background.surface", "#dbe5ef"),
    ("semantic.color.background.panel", "#f7fafd"),
    ("semantic.color.background.elevated", "#fcfdff"),
    ("semantic.color.text.primary", "#131a22"),
    ("semantic.color.text.secondary", "#314255"),
    ("semantic.color.border.subtle", "#c9d4e0"),
    ("semantic.color.border.default", "#75869b"),
    ("semantic.color.icon.primary", "#131a22"),
    ("semantic.color.icon.muted", "#314255"),
    ],
};

pub const LOOPHOLE_STUDIO: ThemeDefinition = ThemeDefinition {
    name: "loophole-studio",
    selector: "[data-theme=\"loophole-studio\"]",
    overrides: &[
    ("semantic.color.background.canvas", "#090d12"),
    ("semantic.color.background.surface", "#101720"),
    ("semantic.color.background.panel", "#151d28"),
    ("semantic.color.background.elevated", "#1a2330"),
    ("semantic.color.background.overlay", "rgba(4, 6, 10, 0.82)"),
    ("semantic.color.text.primary", "#edf3fb"),
    ("semantic.color.text.secondary", "#9fb0c4"),
    ("semantic.color.text.inverse", "#11161d"),
    ("semantic.color.border.subtle", "rgba(159, 176, 196, 0.14)"),
    ("semantic.color.border.default", "rgba(159, 176, 196, 0.24)"),
    ("semantic.color.border.strong", "rgba(159, 176, 196, 0.44)"),
    ("semantic.color.accent.base", "#57a7ff"),
    ("semantic.color.accent.hover", "#7dc4ff"),
    ("semantic.color.accent.focusRing", "#7dc4ff"),
    ("semantic.color.status.success", "#37c78f"),
    ("semantic.color.status.warning", "#f0ba55"),
    ("semantic.color.status.danger", "#ef7c72"),
    ("semantic.color.icon.primary", "#edf3fb"),
    ("semantic.color.icon.muted", "#9fb0c4"),
    ],
};
