// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const audioWaveform: IconNodes = [["path",{"d":"M2 13a2 2 0 0 0 2-2V7a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0V4a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0v-4a2 2 0 0 1 2-2"}]];
