// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const calendar: IconNodes = [["path",{"d":"M8 2v3"}],["path",{"d":"M16 2v3"}],["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2"}],["path",{"d":"M3 9h18"}]];
