// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const checkCircle: IconNodes = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"m9 12 2 2 4-4"}]];
