// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const checkSquare: IconNodes = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"m9 12 2 2 4-4"}]];
