// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const circleX: IconNodes = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"m15 9-6 6"}],["path",{"d":"m9 9 6 6"}]];
