// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const circleCheck: IconNodes = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"m16 9-5.5 5.5L8 12"}]];
