// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const clock: IconNodes = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M12 6v6l4 2"}]];
