// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const code: IconNodes = [["path",{"d":"m16 18 6-6-6-6"}],["path",{"d":"m8 6-6 6 6 6"}]];
