// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const diff: IconNodes = [["path",{"d":"M12 3v14"}],["path",{"d":"M5 10h14"}],["path",{"d":"M5 21h14"}]];
