// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const ellipsis: IconNodes = [["circle",{"cx":"12","cy":"12","r":"1"}],["circle",{"cx":"19","cy":"12","r":"1"}],["circle",{"cx":"5","cy":"12","r":"1"}]];
