// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const heading: IconNodes = [["path",{"d":"M6 12h12"}],["path",{"d":"M6 20V4"}],["path",{"d":"M18 20V4"}]];
