// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const listFilter: IconNodes = [["path",{"d":"M2 5h20"}],["path",{"d":"M6 12h12"}],["path",{"d":"M9 19h6"}]];
