// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const menu: IconNodes = [["path",{"d":"M4 5h16"}],["path",{"d":"M4 12h16"}],["path",{"d":"M4 19h16"}]];
