// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const minimize2: IconNodes = [["path",{"d":"m14 10 7-7"}],["path",{"d":"M20 10h-6V4"}],["path",{"d":"m3 21 7-7"}],["path",{"d":"M4 14h6v6"}]];
