// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const monitor: IconNodes = [["rect",{"width":"20","height":"14","x":"2","y":"3","rx":"2"}],["line",{"x1":"8","x2":"16","y1":"21","y2":"21"}],["line",{"x1":"12","x2":"12","y1":"17","y2":"21"}]];
