// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const moreVertical: IconNodes = [["circle",{"cx":"12","cy":"12","r":"1"}],["circle",{"cx":"12","cy":"5","r":"1"}],["circle",{"cx":"12","cy":"19","r":"1"}]];
