// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const pause: IconNodes = [["rect",{"x":"14","y":"3","width":"5","height":"18","rx":"1"}],["rect",{"x":"5","y":"3","width":"5","height":"18","rx":"1"}]];
