// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const search: IconNodes = [["path",{"d":"m21 21-4.34-4.34"}],["circle",{"cx":"11","cy":"11","r":"8"}]];
