// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const squareCheck: IconNodes = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"m16 9-5.5 5.5L8 12"}]];
