// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const terminal: IconNodes = [["path",{"d":"M12 19h8"}],["path",{"d":"m4 17 6-6-6-6"}]];
