// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const trendingDown: IconNodes = [["path",{"d":"M16 17h6v-6"}],["path",{"d":"m22 17-8.5-8.5-5 5L2 7"}]];
