// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const undo: IconNodes = [["path",{"d":"M3 7v6h6"}],["path",{"d":"M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13"}]];
