// Generated by scripts/build-default-icons.ts. Do not edit.
import type { IconNodes } from "../types";

export const user: IconNodes = [["path",{"d":"M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"}],["circle",{"cx":"12","cy":"7","r":"4"}]];
