export {
  SEGMENTED_AXIS_MAX_OPTIONS,
  applicableAxes,
  axesForModel,
  axisAccepts,
  axisControlKind,
  axisDefaultValue,
  axisSummaryFragment,
  axisValue,
  groupHeadingFor,
  initialSelection,
  modelLabel,
  resolveSelection,
  summaryText,
} from "@inflatable-cookie/poodle-core";
