import { useRef, useState, type CSSProperties, type KeyboardEvent, type PointerEvent } from "react";
import { createModMatrixContext, formatAudioValue, modMatrixTransition, modMatrixVisualState, type ModMatrixCell, type ModMatrixContext, type ModMatrixEffect, type ModMatrixHeader } from "@inflatable-cookie/poodle-core";
import "@inflatable-cookie/poodle-core/styles/mod-matrix-grid.css";
import { ModMatrixVisual } from "./audio/ModMatrixVisual";
import { useAudioPresentation, type AudioPresentationProps } from "./audio/useAudioPresentation";
export interface ModMatrixGridProps extends AudioPresentationProps { sources?: ModMatrixHeader[]; destinations?: ModMatrixHeader[]; cells?: ModMatrixCell[]; step?: number; disabled?: boolean; ariaLabel?: string | null; onCellChange?: (cell: ModMatrixCell) => void; onCellCommit?: (cell: ModMatrixCell) => void; onGestureBegin?: () => void; onGestureEnd?: () => void; }
export function ModMatrixGrid({ size, sizeRole, density, sources = [], destinations = [], cells, step = .01, disabled = false, ariaLabel = "Modulation matrix", onCellChange, onCellCommit, onGestureBegin, onGestureEnd }: ModMatrixGridProps) {
  const presentation = useAudioPresentation({ size, sizeRole, density }); const [machine, setMachine] = useState(createModMatrixContext); const [uncontrolled, setUncontrolled] = useState<ModMatrixCell[]>([]); const root = useRef<HTMLDivElement>(null); const dragPointer = useRef<number | null>(null); const dragTarget = useRef<HTMLElement | null>(null); const currentCells = cells ?? uncontrolled; const context: ModMatrixContext = createModMatrixContext({ ...machine, sources, destinations, cells: currentCells, step, disabled }); const visualState = modMatrixVisualState(context);
  function run(effects: ModMatrixEffect[], next: ModMatrixContext) { for (const effect of effects) { if (effect.type === "emitCellChange" || effect.type === "emitCellCommit") { if (cells === undefined) setUncontrolled(next.cells); effect.type === "emitCellChange" ? onCellChange?.(effect.cell) : onCellCommit?.(effect.cell); } else if (effect.type === "beginGesture") onGestureBegin?.(); else onGestureEnd?.(); } }
  function send(event: Parameters<typeof modMatrixTransition>[1]) { const result = modMatrixTransition(context, event); setMachine(result.context); run(result.effects, result.context); }
  function pointerDown(event: PointerEvent<HTMLDivElement>) { if (event.button !== 0 || disabled || !root.current) return; const target = (event.target as Element).closest<HTMLElement>(".poodle-mod-matrix-grid-visual__cell"); if (!target || !root.current.contains(target)) return; const row = sources.findIndex((source) => source.id === target.dataset.sourceId); const column = destinations.findIndex((destination) => destination.id === target.dataset.destinationId); if (row < 0 || column < 0) return; const rect = target.getBoundingClientRect(); event.preventDefault(); dragPointer.current = event.pointerId; dragTarget.current = target; root.current.setPointerCapture(event.pointerId); send({ type: "DRAG_BEGIN", row, column, amountNorm: Math.min(Math.max(1 - (event.clientY - rect.top) / Math.max(rect.height, 1), 0), 1), fine: event.shiftKey }); root.current.querySelectorAll<HTMLButtonElement>(".poodle-mod-matrix-grid__control")[row * destinations.length + column]?.focus(); }
  function pointerMove(event: PointerEvent<HTMLDivElement>) { if (dragPointer.current !== event.pointerId || !dragTarget.current) return; const rect = dragTarget.current.getBoundingClientRect(); send({ type: "DRAG_MOVE", amountNorm: Math.min(Math.max(1 - (event.clientY - rect.top) / Math.max(rect.height, 1), 0), 1), fine: event.shiftKey }); }
  function pointerEnd(event: PointerEvent<HTMLDivElement>) { if (dragPointer.current === event.pointerId) { dragPointer.current = null; dragTarget.current = null; send({ type: "DRAG_END" }); } }
  function key(event: KeyboardEvent<HTMLDivElement>) { if (event.key.startsWith("Arrow")) { event.preventDefault(); send({ type: "MOVE_FOCUS", rows: event.key === "ArrowDown" ? 1 : event.key === "ArrowUp" ? -1 : 0, columns: event.key === "ArrowRight" ? 1 : event.key === "ArrowLeft" ? -1 : 0 }); } else if (event.key === "Home" || event.key === "End") { event.preventDefault(); send({ type: "BOUND_FOCUS", bound: event.ctrlKey ? (event.key === "Home" ? "grid-start" : "grid-end") : (event.key === "Home" ? "row-start" : "row-end") }); } else if (event.key === " ") { event.preventDefault(); send({ type: "TOGGLE_FOCUSED" }); } else if (event.key === "PageUp" || event.key === "PageDown") { event.preventDefault(); send({ type: "NUDGE_FOCUSED", direction: event.key === "PageUp" ? 1 : -1, fine: event.shiftKey }); } }
  return <div ref={root} className="poodle-mod-matrix-grid" role="group" aria-label={ariaLabel ?? undefined} aria-disabled={disabled} data-scope="mod-matrix-grid" data-part="root" data-size={presentation.size} data-density={presentation.density} style={{ "--poodle-mod-columns": destinations.length } as CSSProperties} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={pointerEnd}>
    <ModMatrixVisual visualState={visualState} />
    <div className="poodle-mod-matrix-grid__controls" role="grid" aria-label={ariaLabel ?? undefined} onKeyDown={key}>{sources.map((source, row) => <div className="poodle-mod-matrix-grid__row" role="row" key={source.id}>{visualState.cells.filter((cell) => cell.sourceId === source.id).map((cell, column) => <button key={`${cell.sourceId}:${cell.destinationId}`} className="poodle-mod-matrix-grid__control" type="button" role="gridcell" disabled={disabled} aria-label={`${source.label} to ${destinations[column]?.label ?? cell.destinationId}, ${cell.enabled ? "enabled" : "disabled"}, ${formatAudioValue(cell.amount, { type: "number", decimals: 2 })}, range ${formatAudioValue(cell.parameters.min, { type: "number", decimals: 2 })} to ${formatAudioValue(cell.parameters.max, { type: "number", decimals: 2 })}`} aria-selected={cell.enabled} tabIndex={cell.focused || (row === 0 && column === 0 && !visualState.focus) ? 0 : -1} onFocus={() => send({ type: "FOCUS_CELL", row, column })} />)}</div>)}</div>
  </div>;
}
