import { useRef, useState, type KeyboardEvent, type PointerEvent } from "react";
import { createWaveformContext, waveformPointToSample, waveformTransition, waveformVisualState, type WaveformContext, type WaveformEffect, type WaveformPeakPyramid, type WaveformSelection } from "@inflatable-cookie/poodle-core";
import "@inflatable-cookie/poodle-core/styles/waveform-display.css";
import { WaveformVisual } from "./audio/WaveformVisual";
import { useAudioPresentation, type AudioPresentationProps } from "./audio/useAudioPresentation";
export interface WaveformDisplayProps extends AudioPresentationProps { pyramid?: WaveformPeakPyramid; visibleStart?: number; visibleEnd?: number; cursorSample?: number | null; selection?: WaveformSelection | null; columnCount?: number; disabled?: boolean; ariaLabel?: string | null; onCursorChange?: (sample: number) => void; onSelectionChange?: (selection: WaveformSelection | null) => void; onSelectionCommit?: (selection: WaveformSelection | null) => void; }
export function WaveformDisplay({ size, sizeRole, density, pyramid = { sampleCount: 0, levels: [] }, visibleStart = 0, visibleEnd = pyramid.sampleCount, cursorSample, selection, columnCount = 512, disabled = false, ariaLabel = "Waveform", onCursorChange, onSelectionChange, onSelectionCommit }: WaveformDisplayProps) {
  const presentation = useAudioPresentation({ size, sizeRole, density }); const [machine, setMachine] = useState(createWaveformContext); const [uncontrolled, setUncontrolled] = useState<{ cursor: number | null; selection: WaveformSelection | null }>({ cursor: null, selection: null }); const root = useRef<HTMLDivElement>(null); const activePointer = useRef<number | null>(null); const currentCursor = cursorSample === undefined ? uncontrolled.cursor : cursorSample; const currentSelection = selection === undefined ? uncontrolled.selection : selection;
  const context: WaveformContext = createWaveformContext({ ...machine, pyramid, visibleStart, visibleEnd, cursorSample: currentCursor, selection: currentSelection, columnCount, disabled }); const visualState = waveformVisualState(context);
  function run(effects: WaveformEffect[]) { for (const effect of effects) { if (effect.type === "emitCursorChange") { if (cursorSample === undefined) setUncontrolled((state) => ({ ...state, cursor: effect.sample })); onCursorChange?.(effect.sample); } else { if (selection === undefined) setUncontrolled((state) => ({ ...state, selection: effect.selection })); effect.type === "emitSelectionChange" ? onSelectionChange?.(effect.selection) : onSelectionCommit?.(effect.selection); } } }
  function send(event: Parameters<typeof waveformTransition>[1]) { const result = waveformTransition(context, event); setMachine(result.context); run(result.effects); }
  function sample(event: PointerEvent<HTMLDivElement>) { return waveformPointToSample({ x: event.clientX, y: event.clientY }, root.current!.getBoundingClientRect(), visibleStart, visibleEnd); }
  function down(event: PointerEvent<HTMLDivElement>) { if (event.button !== 0 || disabled || !root.current) return; event.preventDefault(); activePointer.current = event.pointerId; root.current.setPointerCapture(event.pointerId); send({ type: "SELECT_BEGIN", sample: sample(event) }); }
  function move(event: PointerEvent<HTMLDivElement>) { if (activePointer.current === event.pointerId) send({ type: "SELECT_MOVE", sample: sample(event) }); }
  function end(event: PointerEvent<HTMLDivElement>) { if (activePointer.current === event.pointerId) { activePointer.current = null; send({ type: "SELECT_END" }); } }
  function key(event: KeyboardEvent<HTMLDivElement>) { if (event.key === "ArrowLeft" || event.key === "ArrowRight") { event.preventDefault(); send({ type: "MOVE_CURSOR", delta: event.key === "ArrowRight" ? 1 : -1, extend: event.shiftKey }); } else if (event.key === "Home" || event.key === "End") { event.preventDefault(); send({ type: "BOUND_CURSOR", bound: event.key === "Home" ? "start" : "end", extend: event.shiftKey }); } else if (event.key === "Escape") { event.preventDefault(); send({ type: "CLEAR_SELECTION" }); } }
  const summary = `${ariaLabel ?? "Waveform"}, samples ${visibleStart} to ${visibleEnd}${currentCursor === null ? "" : `, cursor ${currentCursor}`}${currentSelection === null ? "" : `, selection ${currentSelection.start} to ${currentSelection.end}`}`;
  return <div ref={root} className="poodle-waveform-display" role="slider" aria-label={summary} aria-disabled={disabled} aria-valuemin={visibleStart} aria-valuemax={Math.max(visibleEnd - 1, visibleStart)} aria-valuenow={currentCursor ?? visibleStart} aria-valuetext={summary} tabIndex={disabled ? undefined : 0} data-scope="waveform-display" data-part="root" data-size={presentation.size} data-density={presentation.density} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onFocus={() => send({ type: "FOCUS", value: true })} onBlur={() => send({ type: "FOCUS", value: false })} onKeyDown={key}><WaveformVisual visualState={visualState} /></div>;
}
