// Generated by scripts/build-default-icons.ts. Do not edit.
/** Legacy and shorthand names mapped to canonical Lucide names. */
export const iconAliases: Readonly<Record<string, string>> = {
  "alert-circle": "circle-alert",
  "alert-triangle": "triangle-alert",
  "check-circle": "circle-check",
  "check-square": "square-check",
  "circle-help": "circle-question-mark",
  "edit": "pencil",
  "file-question": "file-question-mark",
  "filter": "list-filter",
  "help-circle": "circle-question-mark",
  "more-horizontal": "ellipsis",
  "more-vertical": "ellipsis-vertical",
  "pause-circle": "circle-pause",
  "spinner": "loader-circle",
  "unlock": "lock-open",
  "x-circle": "circle-x"
};
