#!/usr/bin/env node

import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

export function selectIconSet(catalogue, names) {
  const selected = {};
  const missing = [];

  for (const name of [...new Set(names)].sort()) {
    const nodes = catalogue[name];
    if (!nodes) {
      missing.push(name);
      continue;
    }
    selected[name] = nodes;
  }

  if (missing.length > 0) {
    throw new Error(`Unknown Lucide icon name(s): ${missing.join(", ")}`);
  }

  return selected;
}

export function renderIconSetModule(iconSet) {
  const reserved = new Set(["delete", "export", "import", "package", "private", "public", "static"]);
  const exportNames = new Set();
  const namedExports = Object.keys(iconSet).map((name) => {
    const camelName = name.replace(/-([a-z0-9])/g, (_, character) => character.toUpperCase());
    const exportName = reserved.has(camelName) ? `${camelName}Icon` : camelName;
    if (!/^[$A-Z_a-z][$\w]*$/.test(exportName) || exportNames.has(exportName)) {
      throw new Error(`Cannot generate a unique JavaScript export for Lucide icon "${name}"`);
    }
    exportNames.add(exportName);
    return `export const ${exportName} = icons[${JSON.stringify(name)}];`;
  });

  return `// Generated by poodle-icons. Do not edit.\ntype IconNodes = [string, Record<string, string>][];\n\nexport const icons: Record<string, IconNodes> = ${JSON.stringify(iconSet, null, 2)};\n\n${namedExports.join("\n")}\n`;
}

function usage() {
  return "Usage: poodle-icons --names <names.json> --out <icons.generated.ts> [--catalogue <icon-nodes.json>]";
}

function parseArgs(argv) {
  const options = {};
  for (let index = 0; index < argv.length; index += 2) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (!flag?.startsWith("--") || !value) throw new Error(usage());
    options[flag.slice(2)] = value;
  }
  if (!options.names || !options.out) throw new Error(usage());
  return options;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const cwd = process.cwd();
  const requireFromConsumer = createRequire(resolve(cwd, "package.json"));
  const cataloguePath = options.catalogue
    ? resolve(cwd, options.catalogue)
    : requireFromConsumer.resolve("lucide-static/icon-nodes.json");
  const namesPath = resolve(cwd, options.names);
  const outputPath = resolve(cwd, options.out);

  const names = JSON.parse(await readFile(namesPath, "utf8"));
  if (!Array.isArray(names) || names.some((name) => typeof name !== "string")) {
    throw new Error(`${options.names} must contain a JSON array of icon names`);
  }

  const catalogue = JSON.parse(await readFile(cataloguePath, "utf8"));
  const iconSet = selectIconSet(catalogue, names);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderIconSetModule(iconSet));
  console.log(`Wrote ${Object.keys(iconSet).length} icons to ${options.out}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await main();
}
