// Generated by scripts/build-default-icons.ts. Do not edit.
import { alertCircle } from "./icons/alert-circle";
import { alertTriangle } from "./icons/alert-triangle";
import { arrowDown } from "./icons/arrow-down";
import { arrowLeft } from "./icons/arrow-left";
import { arrowRight } from "./icons/arrow-right";
import { arrowUp } from "./icons/arrow-up";
import { arrowUpDown } from "./icons/arrow-up-down";
import { bell } from "./icons/bell";
import { bold } from "./icons/bold";
import { calendar } from "./icons/calendar";
import { check } from "./icons/check";
import { checkCheck } from "./icons/check-check";
import { checkCircle } from "./icons/check-circle";
import { checkSquare } from "./icons/check-square";
import { chevronDown } from "./icons/chevron-down";
import { chevronLeft } from "./icons/chevron-left";
import { chevronRight } from "./icons/chevron-right";
import { chevronUp } from "./icons/chevron-up";
import { circle } from "./icons/circle";
import { circleAlert } from "./icons/circle-alert";
import { circleCheck } from "./icons/circle-check";
import { circleHelp } from "./icons/circle-help";
import { circlePause } from "./icons/circle-pause";
import { circleQuestionMark } from "./icons/circle-question-mark";
import { circleX } from "./icons/circle-x";
import { clock } from "./icons/clock";
import { cloudOff } from "./icons/cloud-off";
import { code } from "./icons/code";
import { columns2 } from "./icons/columns-2";
import { columns3 } from "./icons/columns-3";
import { copy } from "./icons/copy";
import { diff } from "./icons/diff";
import { dot } from "./icons/dot";
import { download } from "./icons/download";
import { edit } from "./icons/edit";
import { ellipsis } from "./icons/ellipsis";
import { ellipsisVertical } from "./icons/ellipsis-vertical";
import { externalLink } from "./icons/external-link";
import { eye } from "./icons/eye";
import { file } from "./icons/file";
import { filePen } from "./icons/file-pen";
import { fileQuestion } from "./icons/file-question";
import { fileQuestionMark } from "./icons/file-question-mark";
import { fileText } from "./icons/file-text";
import { filter } from "./icons/filter";
import { folder } from "./icons/folder";
import { gitBranch } from "./icons/git-branch";
import { gitCommitHorizontal } from "./icons/git-commit-horizontal";
import { gripVertical } from "./icons/grip-vertical";
import { heading } from "./icons/heading";
import { heart } from "./icons/heart";
import { helpCircle } from "./icons/help-circle";
import { image } from "./icons/image";
import { inbox } from "./icons/inbox";
import { info } from "./icons/info";
import { italic } from "./icons/italic";
import { link } from "./icons/link";
import { list } from "./icons/list";
import { listFilter } from "./icons/list-filter";
import { loader } from "./icons/loader";
import { loaderCircle } from "./icons/loader-circle";
import { lock } from "./icons/lock";
import { lockOpen } from "./icons/lock-open";
import { mail } from "./icons/mail";
import { maximize2 } from "./icons/maximize-2";
import { menu } from "./icons/menu";
import { minimize2 } from "./icons/minimize-2";
import { minus } from "./icons/minus";
import { monitorPlay } from "./icons/monitor-play";
import { moreHorizontal } from "./icons/more-horizontal";
import { moreVertical } from "./icons/more-vertical";
import { music } from "./icons/music";
import { packageIcon } from "./icons/package";
import { pause } from "./icons/pause";
import { pauseCircle } from "./icons/pause-circle";
import { pencil } from "./icons/pencil";
import { play } from "./icons/play";
import { plus } from "./icons/plus";
import { quote } from "./icons/quote";
import { redo } from "./icons/redo";
import { refreshCw } from "./icons/refresh-cw";
import { save } from "./icons/save";
import { search } from "./icons/search";
import { settings } from "./icons/settings";
import { spinner } from "./icons/spinner";
import { square } from "./icons/square";
import { squareCheck } from "./icons/square-check";
import { star } from "./icons/star";
import { tag } from "./icons/tag";
import { terminal } from "./icons/terminal";
import { trash2 } from "./icons/trash-2";
import { trendingDown } from "./icons/trending-down";
import { trendingUp } from "./icons/trending-up";
import { triangleAlert } from "./icons/triangle-alert";
import { undo } from "./icons/undo";
import { unlock } from "./icons/unlock";
import { upload } from "./icons/upload";
import { user } from "./icons/user";
import { users } from "./icons/users";
import { volume2 } from "./icons/volume-2";
import { volumeX } from "./icons/volume-x";
import { x } from "./icons/x";
import { xCircle } from "./icons/x-circle";
import type { IconSet } from "./types";

export {
  alertCircle,
  alertTriangle,
  arrowDown,
  arrowLeft,
  arrowRight,
  arrowUp,
  arrowUpDown,
  bell,
  bold,
  calendar,
  check,
  checkCheck,
  checkCircle,
  checkSquare,
  chevronDown,
  chevronLeft,
  chevronRight,
  chevronUp,
  circle,
  circleAlert,
  circleCheck,
  circleHelp,
  circlePause,
  circleQuestionMark,
  circleX,
  clock,
  cloudOff,
  code,
  columns2,
  columns3,
  copy,
  diff,
  dot,
  download,
  edit,
  ellipsis,
  ellipsisVertical,
  externalLink,
  eye,
  file,
  filePen,
  fileQuestion,
  fileQuestionMark,
  fileText,
  filter,
  folder,
  gitBranch,
  gitCommitHorizontal,
  gripVertical,
  heading,
  heart,
  helpCircle,
  image,
  inbox,
  info,
  italic,
  link,
  list,
  listFilter,
  loader,
  loaderCircle,
  lock,
  lockOpen,
  mail,
  maximize2,
  menu,
  minimize2,
  minus,
  monitorPlay,
  moreHorizontal,
  moreVertical,
  music,
  packageIcon,
  pause,
  pauseCircle,
  pencil,
  play,
  plus,
  quote,
  redo,
  refreshCw,
  save,
  search,
  settings,
  spinner,
  square,
  squareCheck,
  star,
  tag,
  terminal,
  trash2,
  trendingDown,
  trendingUp,
  triangleAlert,
  undo,
  unlock,
  upload,
  user,
  users,
  volume2,
  volumeX,
  x,
  xCircle,
};

/** Poodle-owned Lucide names available without operator wiring. */
export const defaultLucideIconSet: IconSet = {
  "alert-circle": alertCircle,
  "alert-triangle": alertTriangle,
  "arrow-down": arrowDown,
  "arrow-left": arrowLeft,
  "arrow-right": arrowRight,
  "arrow-up": arrowUp,
  "arrow-up-down": arrowUpDown,
  "bell": bell,
  "bold": bold,
  "calendar": calendar,
  "check": check,
  "check-check": checkCheck,
  "check-circle": checkCircle,
  "check-square": checkSquare,
  "chevron-down": chevronDown,
  "chevron-left": chevronLeft,
  "chevron-right": chevronRight,
  "chevron-up": chevronUp,
  "circle": circle,
  "circle-alert": circleAlert,
  "circle-check": circleCheck,
  "circle-help": circleHelp,
  "circle-pause": circlePause,
  "circle-question-mark": circleQuestionMark,
  "circle-x": circleX,
  "clock": clock,
  "cloud-off": cloudOff,
  "code": code,
  "columns-2": columns2,
  "columns-3": columns3,
  "copy": copy,
  "diff": diff,
  "dot": dot,
  "download": download,
  "edit": edit,
  "ellipsis": ellipsis,
  "ellipsis-vertical": ellipsisVertical,
  "external-link": externalLink,
  "eye": eye,
  "file": file,
  "file-pen": filePen,
  "file-question": fileQuestion,
  "file-question-mark": fileQuestionMark,
  "file-text": fileText,
  "filter": filter,
  "folder": folder,
  "git-branch": gitBranch,
  "git-commit-horizontal": gitCommitHorizontal,
  "grip-vertical": gripVertical,
  "heading": heading,
  "heart": heart,
  "help-circle": helpCircle,
  "image": image,
  "inbox": inbox,
  "info": info,
  "italic": italic,
  "link": link,
  "list": list,
  "list-filter": listFilter,
  "loader": loader,
  "loader-circle": loaderCircle,
  "lock": lock,
  "lock-open": lockOpen,
  "mail": mail,
  "maximize-2": maximize2,
  "menu": menu,
  "minimize-2": minimize2,
  "minus": minus,
  "monitor-play": monitorPlay,
  "more-horizontal": moreHorizontal,
  "more-vertical": moreVertical,
  "music": music,
  "package": packageIcon,
  "pause": pause,
  "pause-circle": pauseCircle,
  "pencil": pencil,
  "play": play,
  "plus": plus,
  "quote": quote,
  "redo": redo,
  "refresh-cw": refreshCw,
  "save": save,
  "search": search,
  "settings": settings,
  "spinner": spinner,
  "square": square,
  "square-check": squareCheck,
  "star": star,
  "tag": tag,
  "terminal": terminal,
  "trash-2": trash2,
  "trending-down": trendingDown,
  "trending-up": trendingUp,
  "triangle-alert": triangleAlert,
  "undo": undo,
  "unlock": unlock,
  "upload": upload,
  "user": user,
  "users": users,
  "volume-2": volume2,
  "volume-x": volumeX,
  "x": x,
  "x-circle": xCircle,
};
