//! Component registry — generated from the canonical Svelte preview registry
//! (`packages/svelte/preview/src/component-registry.ts`), the source of truth
//! for the component list, tag taxonomy, and descriptions. Keep in sync by
//! re-deriving from that file — do not hand-edit entries.
//!
//! `has_specimen` is jetstream-local: true when `specimens/mod.rs` routes the
//! slug to a live renderer.

/// Sidebar tag taxonomy (mirrors the Svelte `ComponentTag`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ComponentTag {
    Control,
    Input,
    Layout,
    Display,
    Overlay,
    Navigation,
    Data,
    Media,
    Feedback,
    Form,
    Workstation,
}

impl ComponentTag {
    /// Ordered as in the Svelte `tagOrder`.
    pub const ORDER: &[ComponentTag] = &[
        ComponentTag::Control, ComponentTag::Input, ComponentTag::Layout, ComponentTag::Display, ComponentTag::Overlay, ComponentTag::Navigation, ComponentTag::Data, ComponentTag::Media, ComponentTag::Feedback, ComponentTag::Form, ComponentTag::Workstation,
    ];

    /// Sidebar group heading (mirrors the Svelte `tagLabels`).
    pub fn label(self) -> &'static str {
        match self {
            ComponentTag::Control => "Controls",
            ComponentTag::Input => "Inputs",
            ComponentTag::Layout => "Layout",
            ComponentTag::Display => "Display",
            ComponentTag::Overlay => "Overlays",
            ComponentTag::Navigation => "Navigation",
            ComponentTag::Data => "Data",
            ComponentTag::Media => "Media",
            ComponentTag::Feedback => "Feedback",
            ComponentTag::Form => "Form",
            ComponentTag::Workstation => "Workstation",
        }
    }
}

pub struct ComponentEntry {
    pub slug: &'static str,
    pub display_name: &'static str,
    pub description: &'static str,
    pub tag: ComponentTag,
    /// True when a live specimen renderer exists for this component.
    pub has_specimen: bool,
}

/// Every component, ordered by (tag order, display name) — the sidebar order.
pub static ALL_COMPONENTS: &[ComponentEntry] = &[
    ComponentEntry { slug: "button", display_name: "Button", description: "Primary interactive control for triggering actions.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "checkbox", display_name: "Checkbox", description: "Boolean toggle with label, supporting indeterminate state.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "collapse-toggle", display_name: "CollapseToggle", description: "Directional chevron toggle for collapsing/expanding regions.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "icon-button", display_name: "IconButton", description: "Button variant displaying only an icon.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "radio", display_name: "Radio", description: "Single radio option with native name-based group exclusivity.", tag: ComponentTag::Control, has_specimen: false },
    ComponentEntry { slug: "radio-group", display_name: "RadioGroup", description: "Single-selection option group.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "segmented-control", display_name: "SegmentedControl", description: "Inline toggle between mutually exclusive options.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "split-button", display_name: "SplitButton", description: "Button with primary action and dropdown menu.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "switch", display_name: "Switch", description: "Toggle switch for on/off states.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "toggle-group", display_name: "ToggleGroup", description: "Group of mutually exclusive toggle buttons.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "tri-state-switch", display_name: "TriStateSwitch", description: "Three-position switch for on/off/indeterminate.", tag: ComponentTag::Control, has_specimen: true },
    ComponentEntry { slug: "calendar", display_name: "Calendar", description: "Date grid for picking a single date or a date range.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "code-input", display_name: "CodeInput", description: "Code entry with visual digit slots and mask mode.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "color-picker", display_name: "ColorPicker", description: "Color selection with native picker, hex input, and swatches.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "date-picker", display_name: "DatePicker", description: "Date selection with calendar popup.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "date-range-picker", display_name: "DateRangePicker", description: "Start and end date selection with dual calendar.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "date-time-picker", display_name: "DateTimePicker", description: "Combined date and time selection.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "date-time-range-picker", display_name: "DateTimeRangePicker", description: "Start/end date-time range selection.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "date-time-zone-picker", display_name: "DateTimeZonePicker", description: "Date-time picker with timezone awareness.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "duration-input", display_name: "DurationInput", description: "Segmented hours/minutes/seconds duration entry.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "editable-label", display_name: "EditableLabel", description: "Inline text that becomes editable on interaction.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "embed-input", display_name: "EmbedInput", description: "URL or embed code input with provider detection and parsing.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "file-upload", display_name: "FileUpload", description: "File input with drag-and-drop, type filtering, and upload progress.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "number-input", display_name: "NumberInput", description: "Numeric input with optional steppers.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "range-slider", display_name: "RangeSlider", description: "Dual-thumb slider for selecting a numeric range.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "rating", display_name: "Rating", description: "Star-based rating input or display.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "select", display_name: "Select", description: "Dropdown selection from a list of options.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "slider", display_name: "Slider", description: "Single-thumb slider for selecting a numeric value.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "text-input", display_name: "TextInput", description: "Single or multi-line text input with search, slug, and multiline modes.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "time-input", display_name: "TimeInput", description: "Time-of-day input with hour/minute selection.", tag: ComponentTag::Input, has_specimen: false },
    ComponentEntry { slug: "time-zone-select", display_name: "TimeZoneSelect", description: "Timezone selection dropdown.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "token-input", display_name: "TokenInput", description: "Tokenizing text input for badge-like multi-value entry with separator-driven commit semantics.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "box", display_name: "Box", description: "Generic layout container with configurable padding and alignment.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "grid", display_name: "Grid", description: "CSS Grid layout container.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "list-grid", display_name: "ListGrid", description: "Responsive auto-fill grid for card or tile collections with optional header actions.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "region", display_name: "Region", description: "Dashed placeholder block for designating layout areas.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "resize-handle", display_name: "ResizeHandle", description: "Drag and keyboard resize handle for split layouts.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "scroll-shell", display_name: "ScrollShell", description: "Scrollable container with overflow management.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "separator", display_name: "Separator", description: "Visual divider between content sections.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "spacer", display_name: "Spacer", description: "Flexible space for pushing layout elements apart.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "split-view", display_name: "SplitView", description: "Resizable split pane layout with collapse toggles.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "stack", display_name: "Stack", description: "Vertical flex layout container.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "surface", display_name: "Surface", description: "Themed container with background, border, and padding variants.", tag: ComponentTag::Layout, has_specimen: true },
    ComponentEntry { slug: "avatar", display_name: "Avatar", description: "Image or initials avatar for user identity surfaces.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "code", display_name: "Code", description: "Syntax-highlighted code display with copy button.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "detail-item", display_name: "DetailItem", description: "Label-value pair for metadata display.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "embed-preview", display_name: "EmbedPreview", description: "Rich preview card for embedded content.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "eyebrow", display_name: "Eyebrow", description: "Small uppercase label used for section categorization.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "icon", display_name: "Icon", description: "SVG icon accepting direct node data or string names.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "icon-provider", display_name: "IconProvider", description: "Context provider for bulk icon set lookups.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "meta-bar", display_name: "MetaBar", description: "Inline metadata ribbon for compact header facts.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "meta-item", display_name: "MetaItem", description: "Compact labeled metadata item for inline ribbons.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "metric-tile", display_name: "MetricTile", description: "Compact label-value tile for metrics and KPIs.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "pill", display_name: "Pill", description: "Small inline label chip with tone and size variants.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "skeleton", display_name: "Skeleton", description: "Placeholder loading shape for content.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "spinner", display_name: "Spinner", description: "Animated loading indicator with ring and grid variants.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "status-indicator", display_name: "StatusIndicator", description: "Colored dot or icon indicating status.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "text", display_name: "Text", description: "Small text primitive for body, caption, hint, and status copy.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "text-link", display_name: "TextLink", description: "Inline text link or action for prose and metadata copy.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "time-ago", display_name: "TimeAgo", description: "Live-updating relative timestamp display.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "ui-presentation-provider", display_name: "UiPresentationProvider", description: "Scoped provider for semantic density and size defaults.", tag: ComponentTag::Display, has_specimen: true },
    ComponentEntry { slug: "alert-dialog", display_name: "AlertDialog", description: "Focused confirmation modal for destructive actions.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "command-palette", display_name: "CommandPalette", description: "Keyboard-driven command search and execution overlay.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "confirm-action", display_name: "ConfirmAction", description: "Trigger with confirmation prompt before executing.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "context-menu", display_name: "ContextMenu", description: "Right-click triggered menu overlay.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "dialog", display_name: "Dialog", description: "Modal overlay for confirmations, forms, or alerts.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "drawer", display_name: "Drawer", description: "Slide-out panel from a screen edge.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "form-dialog", display_name: "FormDialog", description: "Modal dialog with embedded form and submit/cancel.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "hover-card", display_name: "HoverCard", description: "Rich preview card triggered by hover or focus.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "menu", display_name: "Menu", description: "Dropdown menu with items, separators, and keyboard navigation.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "menubar", display_name: "Menubar", description: "Horizontal menu bar with dropdown sub-menus.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "popover", display_name: "Popover", description: "Anchored overlay for contextual content.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "tooltip", display_name: "Tooltip", description: "Hover/focus-triggered informational overlay.", tag: ComponentTag::Overlay, has_specimen: true },
    ComponentEntry { slug: "breadcrumbs", display_name: "Breadcrumbs", description: "Hierarchical navigation trail showing current location.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "nav-card", display_name: "NavCard", description: "Navigation-oriented card link with icon, badge, and arrow.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "navigation-menu", display_name: "NavigationMenu", description: "Horizontal navigation with dropdown sub-menus.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "pagination", display_name: "Pagination", description: "Page navigation controls for paged data sets.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "pagination-summary", display_name: "PaginationSummary", description: "Textual summary of pagination state.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "sidebar-nav", display_name: "SidebarNav", description: "Grouped sidebar navigation list with active item state.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "tabs", display_name: "Tabs", description: "Tabbed interface with underline, card, pill, and strip variants.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "tree", display_name: "Tree", description: "Hierarchical file-explorer tree with expand/collapse and multi-select.", tag: ComponentTag::Navigation, has_specimen: true },
    ComponentEntry { slug: "accordion", display_name: "Accordion", description: "Expandable disclosure panels with single or multiple selection.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "card", display_name: "Card", description: "Contained surface for grouped content.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "card-radio-group", display_name: "CardRadioGroup", description: "Radio selection across rich card options.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "card-toggle-group", display_name: "CardToggleGroup", description: "Toggleable selection across rich card options.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "collapsible", display_name: "Collapsible", description: "Show/hide content toggle without accordion grouping.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "data-table", display_name: "DataTable", description: "Feature-rich table with sorting, selection, and pagination.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "editable-list", display_name: "EditableList", description: "Editable/reorderable list with add, remove, and drag-and-drop.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "filter-builder", display_name: "FilterBuilder", description: "Popover filter-clause builder with editable pills and AND/OR combinator.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "ref-select", display_name: "RefSelect", description: "Version-control ref chooser with search, a current marker and a loading footer.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "model-picker", display_name: "ModelPicker", description: "Combined model and capability-axis picker in one popover widget.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "agent-chat-input", display_name: "AgentChatInput", description: "Agent composer: editor, control toolbar, context ring, submit/stop action.", tag: ComponentTag::Input, has_specimen: true },
    ComponentEntry { slug: "filter-toolbar", display_name: "FilterToolbar", description: "Toolbar with filter controls for data views.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "list-card", display_name: "ListCard", description: "Structured list item card with snippet-based leading, footer, and trailing composition.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "list-card-counter", display_name: "ListCardCounter", description: "Compact icon-count item used in ListCard footer composition.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "list-container", display_name: "ListContainer", description: "List-page shell with header, filters, and pagination.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "log-list", display_name: "LogList", description: "Operational log viewer and audit activity list.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "order-by", display_name: "OrderBy", description: "Sort-control toolbar for data views.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "picker-shell", display_name: "PickerShell", description: "Container for search-and-select picker workflows.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "relation-picker", display_name: "RelationPicker", description: "Searchable picker for selecting related items.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "selection-summary", display_name: "SelectionSummary", description: "Summary display of current selection state.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "table", display_name: "Table", description: "Static data table with headers, rows, and alignment.", tag: ComponentTag::Data, has_specimen: true },
    ComponentEntry { slug: "audio-player", display_name: "AudioPlayer", description: "Audio playback with transport controls, volume, and speed.", tag: ComponentTag::Media, has_specimen: true },
    ComponentEntry { slug: "media-browse-panel", display_name: "MediaBrowsePanel", description: "Browsable media grid with search and pagination.", tag: ComponentTag::Media, has_specimen: true },
    ComponentEntry { slug: "media-picker", display_name: "MediaPicker", description: "Dialog for browsing and selecting media assets.", tag: ComponentTag::Media, has_specimen: true },
    ComponentEntry { slug: "media-preview", display_name: "MediaPreview", description: "Media asset preview with metadata and fallback.", tag: ComponentTag::Media, has_specimen: true },
    ComponentEntry { slug: "media-thumbnail", display_name: "MediaThumbnail", description: "Compact media thumbnail with overlay metadata.", tag: ComponentTag::Media, has_specimen: true },
    ComponentEntry { slug: "video-player", display_name: "VideoPlayer", description: "Video playback with overlay controls and fullscreen.", tag: ComponentTag::Media, has_specimen: true },
    ComponentEntry { slug: "bulk-action-bar", display_name: "BulkActionBar", description: "Action bar for batch operations on selected items.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "callout", display_name: "Callout", description: "Informational block with tone and optional actions.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "empty-state", display_name: "EmptyState", description: "Placeholder for empty data views with messaging.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "error-boundary", display_name: "ErrorBoundary", description: "Svelte error boundary with retryable empty-state fallback.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "meter", display_name: "Meter", description: "Visual gauge for scalar values within a known range.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "page-loading", display_name: "PageLoading", description: "Full-viewport loading overlay with spinner.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "password-requirements", display_name: "PasswordRequirements", description: "Password-policy checklist driven by caller rules.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "progress", display_name: "Progress", description: "Determinate or indeterminate progress indicator.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "toast-host", display_name: "ToastHost", description: "Store-aware toast host with timer policy.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "toast-stack", display_name: "ToastStack", description: "Stacked transient notification manager.", tag: ComponentTag::Feedback, has_specimen: true },
    ComponentEntry { slug: "block-editor", display_name: "BlockEditor", description: "Block-based content editor shell with pluggable types.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "debug-dialog", display_name: "DebugDialog", description: "Developer-facing JSON debug dialog hidden when no value is supplied.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "field", display_name: "Field", description: "Form field wrapper with label, help text, and validation.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "field-set", display_name: "FieldSet", description: "Semantic fieldset with legend and grid layout.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "form-actions", display_name: "FormActions", description: "Action row for form submit, cancel, and secondary actions.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "form-layout", display_name: "FormLayout", description: "Responsive form grid with error messaging.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "inline-list-section", display_name: "InlineListSection", description: "Compact related-list section for detail and metadata pages.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "markdown-editor", display_name: "MarkdownEditor", description: "Markdown authoring with formatting toolbar and preview.", tag: ComponentTag::Form, has_specimen: true },
    ComponentEntry { slug: "action-discovery-panel", display_name: "ActionDiscoveryPanel", description: "Grouped action list with keyboard navigation.", tag: ComponentTag::Workstation, has_specimen: true },
    ComponentEntry { slug: "app-header", display_name: "AppHeader", description: "Top-level application header with branding and actions.", tag: ComponentTag::Workstation, has_specimen: true },
    ComponentEntry { slug: "detail-section", display_name: "DetailSection", description: "Titled section for grouping detail content.", tag: ComponentTag::Workstation, has_specimen: true },
    ComponentEntry { slug: "detail-section-group", display_name: "DetailSectionGroup", description: "Responsive layout group for multiple peer detail sections.", tag: ComponentTag::Workstation, has_specimen: true },
    ComponentEntry { slug: "detail-shell", display_name: "DetailShell", description: "Full detail page layout with header and sections.", tag: ComponentTag::Workstation, has_specimen: true },
    ComponentEntry { slug: "dock-region", display_name: "DockRegion", description: "Collapsible dock container with tabs and drag-and-drop.", tag: ComponentTag::Workstation, has_specimen: true },
    ComponentEntry { slug: "page-header", display_name: "PageHeader", description: "Page-level header with title, actions, and breadcrumbs.", tag: ComponentTag::Workstation, has_specimen: true },
    ComponentEntry { slug: "status-bar", display_name: "StatusBar", description: "Bottom status bar with leading and trailing slots.", tag: ComponentTag::Workstation, has_specimen: false },
    ComponentEntry { slug: "toolbar", display_name: "Toolbar", description: "Horizontal action bar with grouped controls.", tag: ComponentTag::Workstation, has_specimen: true },
];

/// Number of components with live specimens.
pub fn specimen_count() -> usize {
    ALL_COMPONENTS.iter().filter(|c| c.has_specimen).count()
}
