//! The docs-fragments target — a markdown prop-surface fragment per
//! component, shaped for inclusion in the component contract's `### Public
//! Props` table (the same shape `contract-prop-drift.ts` parses: backticked
//! prop names starting each row). Fragments only — this target never
//! rewrites an existing contract.
//!
//! Output (per model, under the target's output root):
//!
//! - `<component-id>.md` — one fragment per component: the `IR-07` header
//!   as HTML comments (the `//` form is not markdown), then the
//!   `### Public Props` table, props in declaration order (the contract's
//!   own order), components sorted by id.
//!
//! Emission rules (the emitter owns every byte, ruling R2):
//!
//! - the type column uses the same mapping as the TypeScript target —
//!   `string`/`number`/`boolean`, `[t, t]`, `Array<t>`, `unknown`; a
//!   `Shared` prop with a permitted subset renders the **subset union**
//!   (`"danger" \| "default" \| "success"`, the R6.2 constraint surviving
//!   into the artifact, exactly the `button.md` convention); without a
//!   subset it renders the shared type name (`ButtonTone` style);
//! - defaults render like the contract tables: JSON-quoted strings and
//!   members, `format_number` integers (`0`, never `0.0`), pairs and lists
//!   inline; `—` when no default and no expression, `derived` when the
//!   default is a bounded expression (spec 063);
//! - web-only props are included and marked in the Notes column, matching
//!   the TypeScript target's include-and-mark decision (CROSS-03's
//!   exclusion is a portable-spec-surface rule aimed at the Rust spec
//!   target, which no emitter here produces);
//! - string literals use JSON escaping and numbers the fixed locale-
//!   independent formatter, mirroring `ts.rs` — the two targets must never
//!   disagree on a literal.

use poodle_ir::{ComponentDefinition, Identifier, IrModel, Prop, PropType, Value};

use crate::emit::{sort_by_id, EmitTarget, GeneratedFile};
use crate::error::{CodegenError, Result};
use crate::GENERATOR_VERSION;

/// The docs-fragments target.
pub struct DocsFragmentsTarget;

impl EmitTarget for DocsFragmentsTarget {
    fn id(&self) -> &'static str {
        "docs"
    }

    fn output_root(&self) -> &'static str {
        "docs"
    }

    fn render(&self, model: &IrModel, source_path: &str) -> Result<Vec<GeneratedFile>> {
        render_model(model, source_path)
    }
}

/// Renders a model. Public for tests; the bin goes through
/// [`EmitTarget::render`].
pub fn render_model(model: &IrModel, source_path: &str) -> Result<Vec<GeneratedFile>> {
    let header = markdown_header(source_path);

    let components = {
        let mut items: Vec<&ComponentDefinition> = model.components.iter().collect();
        sort_by_id(&mut items, |component| component.id.as_str());
        items
    };

    let mut files = Vec::new();
    for component in &components {
        files.push(GeneratedFile::new(
            format!("{}.md", component.id),
            render_component_fragment(model, component, &header)?,
        ));
    }
    Ok(files)
}

/// The `IR-07` header as HTML comments — same content as [`crate::emit::header`],
/// markdown-legal. No timestamp, no absolute path, no machine identifier.
fn markdown_header(source_path: &str) -> String {
    format!(
        "<!-- Generated by poodle-codegen {GENERATOR_VERSION}. Do not edit manually. -->\n\
         <!-- Source: {source_path} -->\n\
         <!-- IR schema version: {} -->\n\
         <!-- Regenerate with `effigy ir:build`; drift is gated by `effigy ir:check`. -->\n",
        poodle_ir::IR_SCHEMA_VERSION
    )
}

fn render_component_fragment(
    model: &IrModel,
    component: &ComponentDefinition,
    header: &str,
) -> Result<String> {
    let mut out = String::from(header);
    out.push_str("### Public Props\n\n");
    out.push_str("| Prop | Type | Default | Required | Notes |\n");
    out.push_str("|------|------|---------|----------|-------|\n");
    for prop in &component.props {
        let ty = render_prop_type(model, &prop.prop_type, prop.permitted_subset.as_ref())?;
        let default = match (&prop.default, &prop.default_expr) {
            (Some(value), _) => md_value_literal(value),
            (None, Some(_)) => "derived".to_owned(),
            (None, None) => "—".to_owned(),
        };
        let mut notes = collapse_whitespace(&prop.description);
        if prop.web_only {
            notes.push_str("; web-only (CROSS-03)");
        }
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} | {} |\n",
            prop.name,
            ty,
            default,
            if prop.required { "yes" } else { "no" },
            escape_table_cell(&notes),
        ));
    }
    Ok(out)
}

/// One prop's type in the contract's union style. Mirrors the TypeScript
/// target's mapping so the two artifacts never disagree on a type.
fn render_prop_type(
    model: &IrModel,
    prop_type: &PropType,
    subset: Option<&poodle_ir::PermittedSubset>,
) -> Result<String> {
    match prop_type {
        PropType::String => Ok("string".to_owned()),
        PropType::Number => Ok("number".to_owned()),
        PropType::Bool => Ok("boolean".to_owned()),
        PropType::Shared(id) => {
            if let Some(subset) = subset {
                // R6.2: the permitted subset survives into the artifact as
                // the prop's actual value domain — the `button.md`
                // convention.
                let members: Vec<String> = subset
                    .members
                    .iter()
                    .map(|member| ts_string_literal(member.as_str()))
                    .collect();
                Ok(members.join(" \\| "))
            } else {
                Ok(shared_type_name(model, id)?.to_owned())
            }
        }
        PropType::Pair(inner) => {
            let inner = render_prop_type(model, inner, None)?;
            Ok(format!("[{inner}, {inner}]"))
        }
        PropType::List(inner) => {
            let inner = render_prop_type(model, inner, None)?;
            Ok(format!("Array<{inner}>"))
        }
        PropType::Opaque => Ok("unknown".to_owned()),
    }
}

/// Resolves a shared-type id to its Rust-style name. A validated model
/// always resolves; the error path exists so emission never panics.
fn shared_type_name<'a>(model: &'a IrModel, id: &Identifier) -> Result<&'a str> {
    model
        .shared_type(id.as_str())
        .map(|shared| shared.name.as_str())
        .ok_or_else(|| CodegenError::UnresolvedReference {
            what: format!("shared type '{id}'"),
        })
}

/// A JSON-escaped string literal — the same escaping the TypeScript target
/// uses.
fn ts_string_literal(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

/// A default value in the contract's literal style, mirroring `ts.rs`'s
/// `ts_value_literal`.
fn md_value_literal(value: &Value) -> String {
    match value {
        Value::String(s) => ts_string_literal(s),
        Value::Number(n) => format_number(*n),
        Value::Bool(b) => b.to_string(),
        Value::Member(id) => ts_string_literal(id.as_str()),
        Value::Pair(a, b) => {
            format!("[{}, {}]", md_value_literal(a), md_value_literal(b))
        }
        Value::List(items) => {
            let items: Vec<String> = items.iter().map(md_value_literal).collect();
            format!("[{}]", items.join(", "))
        }
        Value::Null => "null".to_owned(),
    }
}

/// Fixed number formatting, mirroring `ts.rs`: integral values print
/// without a fractional part, everything else shortest round-trip — never
/// exponent notation, never locale-dependent.
fn format_number(n: f64) -> String {
    if n.fract() == 0.0 && n.abs() < 1e15 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

/// Collapses runs of whitespace to a single space so table cells stay one
/// line, mirroring `ts.rs`.
fn collapse_whitespace(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Escapes the one character that would break a markdown table cell.
fn escape_table_cell(text: &str) -> String {
    text.replace('|', "\\|")
}
