// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

export const tokens = {
  "primitives": {
    "border": {
      "width": {
        "subtle": "1px",
        "strong": "2px"
      }
    },
    "color": {
      "neutral": {
        "0": "#fcfdff",
        "25": "#f7fafd",
        "50": "#e7eef5",
        "100": "#dbe5ef",
        "200": "#c9d4e0",
        "400": "#75869b",
        "700": "#314255",
        "900": "#131a22"
      },
      "slate": {
        "850": "#1a212c",
        "900": "#11161d",
        "950": "#0b0f14"
      },
      "blue": {
        "400": "#57a7ff",
        "500": "#2d86f3"
      },
      "green": {
        "500": "#1fb67b"
      },
      "amber": {
        "500": "#f0b24d"
      },
      "red": {
        "500": "#e06a5f"
      }
    },
    "space": {
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "8": "32px",
      "10": "40px",
      "12": "48px"
    },
    "size": {
      "control": {
        "sm": "28px",
        "md": "36px",
        "lg": "44px"
      },
      "icon": {
        "sm": "12px",
        "md": "16px",
        "lg": "20px"
      },
      "panel": {
        "header": "40px"
      }
    },
    "stroke": {
      "hairline": "1px",
      "focus": "2px"
    },
    "elevation": {
      "shadow": {
        "sm": "0 4px 12px rgba(17, 22, 29, 0.08)",
        "md": "0 12px 32px rgba(17, 22, 29, 0.16)",
        "lg": "0 24px 60px rgba(11, 15, 20, 0.32)"
      }
    },
    "icon": {
      "size": {
        "sm": "12px",
        "md": "16px",
        "lg": "20px"
      },
      "stroke": {
        "default": "1.5px"
      }
    },
    "motion": {
      "duration": {
        "fast": "120ms",
        "standard": "180ms",
        "slow": "260ms"
      },
      "easing": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "emphasized": "cubic-bezier(0.16, 1, 0.3, 1)"
      }
    },
    "overlay": {
      "z": {
        "base": 100,
        "menu": 400,
        "dialog": 800,
        "toast": 900
      },
      "scrim": {
        "opacity": 0.64
      }
    },
    "radius": {
      "none": "0px",
      "sm": "3px",
      "md": "6px",
      "lg": "10px",
      "pill": "999px"
    },
    "state": {
      "opacity": {
        "disabled": 0.48,
        "muted": 0.72
      }
    },
    "typography": {
      "font": {
        "family": {
          "sans": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
          "mono": "\"IBM Plex Mono\", \"SFMono-Regular\", monospace"
        },
        "weight": {
          "regular": "400",
          "medium": "500",
          "semibold": "600"
        },
        "size": {
          "xs": "11px",
          "sm": "13px",
          "md": "14px",
          "lg": "16px",
          "xl": "20px"
        },
        "lineHeight": {
          "sm": "16px",
          "md": "20px",
          "lg": "24px"
        }
      }
    }
  },
  "semantic": {
    "border": {
      "width": {
        "default": "1px",
        "focus": "2px"
      }
    },
    "color": {
      "background": {
        "canvas": "#e7eef5",
        "surface": "#dbe5ef",
        "panel": "#f7fafd",
        "elevated": "#fcfdff",
        "overlay": "rgba(11, 15, 20, 0.64)"
      },
      "text": {
        "primary": "#131a22",
        "secondary": "#314255",
        "inverse": "#fcfdff"
      },
      "border": {
        "subtle": "#c9d4e0",
        "default": "#75869b",
        "strong": "#314255"
      },
      "accent": {
        "base": "#2d86f3",
        "hover": "#57a7ff",
        "focusRing": "#57a7ff"
      },
      "status": {
        "success": "#1fb67b",
        "warning": "#f0b24d",
        "danger": "#e06a5f"
      },
      "icon": {
        "primary": "#131a22",
        "muted": "#314255"
      }
    },
    "elevation": {
      "surface": "0 4px 12px rgba(17, 22, 29, 0.08)",
      "overlay": "0 12px 32px rgba(17, 22, 29, 0.16)",
      "dialog": "0 24px 60px rgba(11, 15, 20, 0.32)"
    },
    "icon": {
      "size": {
        "default": "16px"
      },
      "stroke": {
        "default": "1.5px"
      }
    },
    "motion": {
      "duration": {
        "interaction": "180ms",
        "overlay": "120ms"
      },
      "easing": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "emphasized": "cubic-bezier(0.16, 1, 0.3, 1)"
      }
    },
    "overlay": {
      "z": {
        "menu": 400,
        "dialog": 800,
        "toast": 900
      },
      "scrimOpacity": 0.64
    },
    "radius": {
      "control": "6px",
      "surface": "10px",
      "pill": "999px"
    },
    "size": {
      "control": {
        "height": "36px",
        "minWidth": "96px"
      },
      "icon": {
        "sm": "12px",
        "md": "16px",
        "lg": "20px"
      },
      "panel": {
        "header": "40px"
      }
    },
    "space": {
      "stack": {
        "sm": "8px",
        "md": "12px",
        "lg": "20px"
      },
      "inline": {
        "sm": "8px",
        "md": "12px",
        "lg": "16px"
      },
      "panel": {
        "x": "16px",
        "y": "12px"
      },
      "control": {
        "x": "12px",
        "y": "8px"
      }
    },
    "state": {
      "opacity": {
        "disabled": 0.48,
        "muted": 0.72
      }
    },
    "typography": {
      "body": {
        "family": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
        "size": "14px",
        "lineHeight": "20px",
        "weight": "400"
      },
      "label": {
        "family": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
        "size": "13px",
        "lineHeight": "16px",
        "weight": "500"
      },
      "heading": {
        "family": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
        "size": "16px",
        "lineHeight": "24px",
        "weight": "600"
      },
      "code": {
        "family": "\"IBM Plex Mono\", \"SFMono-Regular\", monospace",
        "size": "13px",
        "lineHeight": "16px",
        "weight": "400"
      }
    }
  }
} as const;

export const tokenPaths = [
  "primitives.border.width.subtle",
  "primitives.border.width.strong",
  "primitives.color.neutral.0",
  "primitives.color.neutral.25",
  "primitives.color.neutral.50",
  "primitives.color.neutral.100",
  "primitives.color.neutral.200",
  "primitives.color.neutral.400",
  "primitives.color.neutral.700",
  "primitives.color.neutral.900",
  "primitives.color.slate.850",
  "primitives.color.slate.900",
  "primitives.color.slate.950",
  "primitives.color.blue.400",
  "primitives.color.blue.500",
  "primitives.color.green.500",
  "primitives.color.amber.500",
  "primitives.color.red.500",
  "primitives.space.0",
  "primitives.space.1",
  "primitives.space.2",
  "primitives.space.3",
  "primitives.space.4",
  "primitives.space.5",
  "primitives.space.6",
  "primitives.space.8",
  "primitives.space.10",
  "primitives.space.12",
  "primitives.size.control.sm",
  "primitives.size.control.md",
  "primitives.size.control.lg",
  "primitives.size.icon.sm",
  "primitives.size.icon.md",
  "primitives.size.icon.lg",
  "primitives.size.panel.header",
  "primitives.stroke.hairline",
  "primitives.stroke.focus",
  "primitives.elevation.shadow.sm",
  "primitives.elevation.shadow.md",
  "primitives.elevation.shadow.lg",
  "primitives.icon.size.sm",
  "primitives.icon.size.md",
  "primitives.icon.size.lg",
  "primitives.icon.stroke.default",
  "primitives.motion.duration.fast",
  "primitives.motion.duration.standard",
  "primitives.motion.duration.slow",
  "primitives.motion.easing.standard",
  "primitives.motion.easing.emphasized",
  "primitives.overlay.z.base",
  "primitives.overlay.z.menu",
  "primitives.overlay.z.dialog",
  "primitives.overlay.z.toast",
  "primitives.overlay.scrim.opacity",
  "primitives.radius.none",
  "primitives.radius.sm",
  "primitives.radius.md",
  "primitives.radius.lg",
  "primitives.radius.pill",
  "primitives.state.opacity.disabled",
  "primitives.state.opacity.muted",
  "primitives.typography.font.family.sans",
  "primitives.typography.font.family.mono",
  "primitives.typography.font.weight.regular",
  "primitives.typography.font.weight.medium",
  "primitives.typography.font.weight.semibold",
  "primitives.typography.font.size.xs",
  "primitives.typography.font.size.sm",
  "primitives.typography.font.size.md",
  "primitives.typography.font.size.lg",
  "primitives.typography.font.size.xl",
  "primitives.typography.font.lineHeight.sm",
  "primitives.typography.font.lineHeight.md",
  "primitives.typography.font.lineHeight.lg",
  "semantic.border.width.default",
  "semantic.border.width.focus",
  "semantic.color.background.canvas",
  "semantic.color.background.surface",
  "semantic.color.background.panel",
  "semantic.color.background.elevated",
  "semantic.color.background.overlay",
  "semantic.color.text.primary",
  "semantic.color.text.secondary",
  "semantic.color.text.inverse",
  "semantic.color.border.subtle",
  "semantic.color.border.default",
  "semantic.color.border.strong",
  "semantic.color.accent.base",
  "semantic.color.accent.hover",
  "semantic.color.accent.focusRing",
  "semantic.color.status.success",
  "semantic.color.status.warning",
  "semantic.color.status.danger",
  "semantic.color.icon.primary",
  "semantic.color.icon.muted",
  "semantic.elevation.surface",
  "semantic.elevation.overlay",
  "semantic.elevation.dialog",
  "semantic.icon.size.default",
  "semantic.icon.stroke.default",
  "semantic.motion.duration.interaction",
  "semantic.motion.duration.overlay",
  "semantic.motion.easing.standard",
  "semantic.motion.easing.emphasized",
  "semantic.overlay.z.menu",
  "semantic.overlay.z.dialog",
  "semantic.overlay.z.toast",
  "semantic.overlay.scrimOpacity",
  "semantic.radius.control",
  "semantic.radius.surface",
  "semantic.radius.pill",
  "semantic.size.control.height",
  "semantic.size.control.minWidth",
  "semantic.size.icon.sm",
  "semantic.size.icon.md",
  "semantic.size.icon.lg",
  "semantic.size.panel.header",
  "semantic.space.stack.sm",
  "semantic.space.stack.md",
  "semantic.space.stack.lg",
  "semantic.space.inline.sm",
  "semantic.space.inline.md",
  "semantic.space.inline.lg",
  "semantic.space.panel.x",
  "semantic.space.panel.y",
  "semantic.space.control.x",
  "semantic.space.control.y",
  "semantic.state.opacity.disabled",
  "semantic.state.opacity.muted",
  "semantic.typography.body.family",
  "semantic.typography.body.size",
  "semantic.typography.body.lineHeight",
  "semantic.typography.body.weight",
  "semantic.typography.label.family",
  "semantic.typography.label.size",
  "semantic.typography.label.lineHeight",
  "semantic.typography.label.weight",
  "semantic.typography.heading.family",
  "semantic.typography.heading.size",
  "semantic.typography.heading.lineHeight",
  "semantic.typography.heading.weight",
  "semantic.typography.code.family",
  "semantic.typography.code.size",
  "semantic.typography.code.lineHeight",
  "semantic.typography.code.weight"
] as const;

export const cssVars = {
  "semantic.border.width.default": "--pug-border-width-default",
  "semantic.border.width.focus": "--pug-border-width-focus",
  "semantic.color.background.canvas": "--pug-color-background-canvas",
  "semantic.color.background.surface": "--pug-color-background-surface",
  "semantic.color.background.panel": "--pug-color-background-panel",
  "semantic.color.background.elevated": "--pug-color-background-elevated",
  "semantic.color.background.overlay": "--pug-color-background-overlay",
  "semantic.color.text.primary": "--pug-color-text-primary",
  "semantic.color.text.secondary": "--pug-color-text-secondary",
  "semantic.color.text.inverse": "--pug-color-text-inverse",
  "semantic.color.border.subtle": "--pug-color-border-subtle",
  "semantic.color.border.default": "--pug-color-border-default",
  "semantic.color.border.strong": "--pug-color-border-strong",
  "semantic.color.accent.base": "--pug-color-accent-base",
  "semantic.color.accent.hover": "--pug-color-accent-hover",
  "semantic.color.accent.focusRing": "--pug-color-accent-focusRing",
  "semantic.color.status.success": "--pug-color-status-success",
  "semantic.color.status.warning": "--pug-color-status-warning",
  "semantic.color.status.danger": "--pug-color-status-danger",
  "semantic.color.icon.primary": "--pug-color-icon-primary",
  "semantic.color.icon.muted": "--pug-color-icon-muted",
  "semantic.elevation.surface": "--pug-elevation-surface",
  "semantic.elevation.overlay": "--pug-elevation-overlay",
  "semantic.elevation.dialog": "--pug-elevation-dialog",
  "semantic.icon.size.default": "--pug-icon-size-default",
  "semantic.icon.stroke.default": "--pug-icon-stroke-default",
  "semantic.motion.duration.interaction": "--pug-motion-duration-interaction",
  "semantic.motion.duration.overlay": "--pug-motion-duration-overlay",
  "semantic.motion.easing.standard": "--pug-motion-easing-standard",
  "semantic.motion.easing.emphasized": "--pug-motion-easing-emphasized",
  "semantic.overlay.z.menu": "--pug-overlay-z-menu",
  "semantic.overlay.z.dialog": "--pug-overlay-z-dialog",
  "semantic.overlay.z.toast": "--pug-overlay-z-toast",
  "semantic.overlay.scrimOpacity": "--pug-overlay-scrimOpacity",
  "semantic.radius.control": "--pug-radius-control",
  "semantic.radius.surface": "--pug-radius-surface",
  "semantic.radius.pill": "--pug-radius-pill",
  "semantic.size.control.height": "--pug-size-control-height",
  "semantic.size.control.minWidth": "--pug-size-control-minWidth",
  "semantic.size.icon.sm": "--pug-size-icon-sm",
  "semantic.size.icon.md": "--pug-size-icon-md",
  "semantic.size.icon.lg": "--pug-size-icon-lg",
  "semantic.size.panel.header": "--pug-size-panel-header",
  "semantic.space.stack.sm": "--pug-space-stack-sm",
  "semantic.space.stack.md": "--pug-space-stack-md",
  "semantic.space.stack.lg": "--pug-space-stack-lg",
  "semantic.space.inline.sm": "--pug-space-inline-sm",
  "semantic.space.inline.md": "--pug-space-inline-md",
  "semantic.space.inline.lg": "--pug-space-inline-lg",
  "semantic.space.panel.x": "--pug-space-panel-x",
  "semantic.space.panel.y": "--pug-space-panel-y",
  "semantic.space.control.x": "--pug-space-control-x",
  "semantic.space.control.y": "--pug-space-control-y",
  "semantic.state.opacity.disabled": "--pug-state-opacity-disabled",
  "semantic.state.opacity.muted": "--pug-state-opacity-muted",
  "semantic.typography.body.family": "--pug-typography-body-family",
  "semantic.typography.body.size": "--pug-typography-body-size",
  "semantic.typography.body.lineHeight": "--pug-typography-body-lineHeight",
  "semantic.typography.body.weight": "--pug-typography-body-weight",
  "semantic.typography.label.family": "--pug-typography-label-family",
  "semantic.typography.label.size": "--pug-typography-label-size",
  "semantic.typography.label.lineHeight": "--pug-typography-label-lineHeight",
  "semantic.typography.label.weight": "--pug-typography-label-weight",
  "semantic.typography.heading.family": "--pug-typography-heading-family",
  "semantic.typography.heading.size": "--pug-typography-heading-size",
  "semantic.typography.heading.lineHeight": "--pug-typography-heading-lineHeight",
  "semantic.typography.heading.weight": "--pug-typography-heading-weight",
  "semantic.typography.code.family": "--pug-typography-code-family",
  "semantic.typography.code.size": "--pug-typography-code-size",
  "semantic.typography.code.lineHeight": "--pug-typography-code-lineHeight",
  "semantic.typography.code.weight": "--pug-typography-code-weight"
} as const;

export type TokenPath = (typeof tokenPaths)[number];
export type Tokens = typeof tokens;
