// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

export const tokens = {
  "primitives": {
    "border": {
      "width": {
        "subtle": "0.0625rem",
        "strong": "0.125rem"
      }
    },
    "color": {
      "neutral": {
        "0": "#fcfdff",
        "25": "#f7fafd",
        "50": "#e7eef5",
        "100": "#dbe5ef",
        "200": "#c9d4e0",
        "400": "#75869b",
        "700": "#314255",
        "900": "#131a22"
      },
      "slate": {
        "850": "#1a212c",
        "900": "#11161d",
        "950": "#0b0f14"
      },
      "blue": {
        "400": "#57a7ff",
        "500": "#2d86f3"
      },
      "green": {
        "400": "#9fe870",
        "500": "#7fd24d"
      },
      "amber": {
        "400": "#ffca73",
        "500": "#f0b24d"
      },
      "red": {
        "500": "#e06a5f"
      }
    },
    "space": {
      "0": "0rem",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem"
    },
    "size": {
      "control": {
        "xs": "1.5rem",
        "sm": "1.75rem",
        "md": "2.25rem",
        "lg": "2.75rem",
        "xl": "3.25rem"
      },
      "icon": {
        "xs": "0.625rem",
        "sm": "0.75rem",
        "md": "1rem",
        "lg": "1.25rem",
        "xl": "1.5rem"
      },
      "panel": {
        "header": "2.5rem"
      }
    },
    "stroke": {
      "hairline": "0.0625rem",
      "focus": "0.125rem"
    },
    "elevation": {
      "shadow": {
        "sm": "0 0.25rem 0.75rem rgba(17, 22, 29, 0.08)",
        "md": "0 0.75rem 2rem rgba(17, 22, 29, 0.16)",
        "lg": "0 1.5rem 3.75rem rgba(11, 15, 20, 0.32)"
      }
    },
    "icon": {
      "size": {
        "xs": "0.625rem",
        "sm": "0.75rem",
        "md": "1rem",
        "lg": "1.25rem",
        "xl": "1.5rem"
      },
      "stroke": {
        "default": "0.0938rem"
      }
    },
    "motion": {
      "duration": {
        "fast": "120ms",
        "standard": "180ms",
        "slow": "260ms"
      },
      "easing": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "emphasized": "cubic-bezier(0.16, 1, 0.3, 1)"
      }
    },
    "overlay": {
      "z": {
        "base": 100,
        "menu": 400,
        "dialog": 800,
        "toast": 900
      },
      "scrim": {
        "opacity": 0.64
      }
    },
    "radius": {
      "none": "0rem",
      "sm": "0.1875rem",
      "md": "0.375rem",
      "lg": "0.625rem",
      "pill": "999rem"
    },
    "state": {
      "opacity": {
        "disabled": 0.48,
        "muted": 0.72
      }
    },
    "typography": {
      "font": {
        "family": {
          "sans": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
          "mono": "\"IBM Plex Mono\", \"SFMono-Regular\", monospace"
        },
        "weight": {
          "regular": "400",
          "medium": "500",
          "semibold": "600"
        },
        "size": {
          "xs": "0.6875rem",
          "sm": "0.8125rem",
          "md": "0.875rem",
          "lg": "1rem",
          "xl": "1.25rem"
        },
        "lineHeight": {
          "sm": "1rem",
          "md": "1.25rem",
          "lg": "1.5rem"
        }
      }
    }
  },
  "semantic": {
    "border": {
      "width": {
        "default": "0.0625rem",
        "focus": "0.125rem"
      }
    },
    "color": {
      "background": {
        "canvas": "#e7eef5",
        "surface": "#dbe5ef",
        "panel": "#f7fafd",
        "elevated": "#fcfdff",
        "overlay": "rgba(11, 15, 20, 0.64)"
      },
      "text": {
        "primary": "#131a22",
        "secondary": "#314255",
        "inverse": "#fcfdff"
      },
      "border": {
        "subtle": "#c9d4e0",
        "default": "#75869b",
        "strong": "#314255"
      },
      "accent": {
        "base": "#2d86f3",
        "hover": "#57a7ff",
        "focusRing": "#57a7ff"
      },
      "status": {
        "success": "#7fd24d",
        "warning": "#f0b24d",
        "danger": "#e06a5f"
      },
      "icon": {
        "primary": "#131a22",
        "muted": "#314255"
      }
    },
    "elevation": {
      "surface": "0 0.25rem 0.75rem rgba(17, 22, 29, 0.08)",
      "overlay": "0 0.75rem 2rem rgba(17, 22, 29, 0.16)",
      "dialog": "0 1.5rem 3.75rem rgba(11, 15, 20, 0.32)"
    },
    "icon": {
      "size": {
        "default": "1rem"
      },
      "stroke": {
        "default": "0.0938rem"
      }
    },
    "motion": {
      "duration": {
        "interaction": "180ms",
        "overlay": "120ms"
      },
      "easing": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "emphasized": "cubic-bezier(0.16, 1, 0.3, 1)"
      }
    },
    "overlay": {
      "z": {
        "menu": 400,
        "dialog": 800,
        "toast": 900
      },
      "scrimOpacity": 0.64
    },
    "radius": {
      "control": "0.375rem",
      "surface": "0.625rem",
      "pill": "999rem"
    },
    "size": {
      "control": {
        "height": "2.25rem",
        "minWidth": "6rem"
      },
      "icon": {
        "xs": "0.625rem",
        "sm": "0.75rem",
        "md": "1rem",
        "lg": "1.25rem",
        "xl": "1.5rem"
      },
      "panel": {
        "header": "2.5rem"
      }
    },
    "space": {
      "stack": {
        "sm": "0.5rem",
        "md": "0.75rem",
        "lg": "1.25rem"
      },
      "inline": {
        "sm": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem"
      },
      "panel": {
        "x": "1rem",
        "y": "0.75rem"
      },
      "control": {
        "x": "0.75rem",
        "y": "0.5rem"
      }
    },
    "state": {
      "opacity": {
        "disabled": 0.48,
        "muted": 0.72
      }
    },
    "typography": {
      "body": {
        "family": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
        "size": "0.875rem",
        "lineHeight": "1.25rem",
        "weight": "400"
      },
      "label": {
        "family": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
        "size": "0.8125rem",
        "lineHeight": "1rem",
        "weight": "500"
      },
      "caption": {
        "family": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
        "size": "0.6875rem",
        "lineHeight": "1rem",
        "weight": "500"
      },
      "heading": {
        "family": "\"Inter\", \"SF Pro Display\", system-ui, sans-serif",
        "size": "1rem",
        "lineHeight": "1.5rem",
        "weight": "600"
      },
      "code": {
        "family": "\"IBM Plex Mono\", \"SFMono-Regular\", monospace",
        "adjustmentRatio": 0.8125,
        "size": "0.8125rem",
        "lineHeight": "1rem",
        "weight": "400"
      }
    }
  }
} as const;

export const tokenPaths = [
  "primitives.border.width.subtle",
  "primitives.border.width.strong",
  "primitives.color.neutral.0",
  "primitives.color.neutral.25",
  "primitives.color.neutral.50",
  "primitives.color.neutral.100",
  "primitives.color.neutral.200",
  "primitives.color.neutral.400",
  "primitives.color.neutral.700",
  "primitives.color.neutral.900",
  "primitives.color.slate.850",
  "primitives.color.slate.900",
  "primitives.color.slate.950",
  "primitives.color.blue.400",
  "primitives.color.blue.500",
  "primitives.color.green.400",
  "primitives.color.green.500",
  "primitives.color.amber.400",
  "primitives.color.amber.500",
  "primitives.color.red.500",
  "primitives.space.0",
  "primitives.space.1",
  "primitives.space.2",
  "primitives.space.3",
  "primitives.space.4",
  "primitives.space.5",
  "primitives.space.6",
  "primitives.space.8",
  "primitives.space.10",
  "primitives.space.12",
  "primitives.size.control.xs",
  "primitives.size.control.sm",
  "primitives.size.control.md",
  "primitives.size.control.lg",
  "primitives.size.control.xl",
  "primitives.size.icon.xs",
  "primitives.size.icon.sm",
  "primitives.size.icon.md",
  "primitives.size.icon.lg",
  "primitives.size.icon.xl",
  "primitives.size.panel.header",
  "primitives.stroke.hairline",
  "primitives.stroke.focus",
  "primitives.elevation.shadow.sm",
  "primitives.elevation.shadow.md",
  "primitives.elevation.shadow.lg",
  "primitives.icon.size.xs",
  "primitives.icon.size.sm",
  "primitives.icon.size.md",
  "primitives.icon.size.lg",
  "primitives.icon.size.xl",
  "primitives.icon.stroke.default",
  "primitives.motion.duration.fast",
  "primitives.motion.duration.standard",
  "primitives.motion.duration.slow",
  "primitives.motion.easing.standard",
  "primitives.motion.easing.emphasized",
  "primitives.overlay.z.base",
  "primitives.overlay.z.menu",
  "primitives.overlay.z.dialog",
  "primitives.overlay.z.toast",
  "primitives.overlay.scrim.opacity",
  "primitives.radius.none",
  "primitives.radius.sm",
  "primitives.radius.md",
  "primitives.radius.lg",
  "primitives.radius.pill",
  "primitives.state.opacity.disabled",
  "primitives.state.opacity.muted",
  "primitives.typography.font.family.sans",
  "primitives.typography.font.family.mono",
  "primitives.typography.font.weight.regular",
  "primitives.typography.font.weight.medium",
  "primitives.typography.font.weight.semibold",
  "primitives.typography.font.size.xs",
  "primitives.typography.font.size.sm",
  "primitives.typography.font.size.md",
  "primitives.typography.font.size.lg",
  "primitives.typography.font.size.xl",
  "primitives.typography.font.lineHeight.sm",
  "primitives.typography.font.lineHeight.md",
  "primitives.typography.font.lineHeight.lg",
  "border.width.default",
  "border.width.focus",
  "color.background.canvas",
  "color.background.surface",
  "color.background.panel",
  "color.background.elevated",
  "color.background.overlay",
  "color.text.primary",
  "color.text.secondary",
  "color.text.inverse",
  "color.border.subtle",
  "color.border.default",
  "color.border.strong",
  "color.accent.base",
  "color.accent.hover",
  "color.accent.focusRing",
  "color.status.success",
  "color.status.warning",
  "color.status.danger",
  "color.icon.primary",
  "color.icon.muted",
  "elevation.surface",
  "elevation.overlay",
  "elevation.dialog",
  "icon.size.default",
  "icon.stroke.default",
  "motion.duration.interaction",
  "motion.duration.overlay",
  "motion.easing.standard",
  "motion.easing.emphasized",
  "overlay.z.menu",
  "overlay.z.dialog",
  "overlay.z.toast",
  "overlay.scrimOpacity",
  "radius.control",
  "radius.surface",
  "radius.pill",
  "size.control.height",
  "size.control.minWidth",
  "size.icon.xs",
  "size.icon.sm",
  "size.icon.md",
  "size.icon.lg",
  "size.icon.xl",
  "size.panel.header",
  "space.stack.sm",
  "space.stack.md",
  "space.stack.lg",
  "space.inline.sm",
  "space.inline.md",
  "space.inline.lg",
  "space.panel.x",
  "space.panel.y",
  "space.control.x",
  "space.control.y",
  "state.opacity.disabled",
  "state.opacity.muted",
  "typography.body.family",
  "typography.body.size",
  "typography.body.lineHeight",
  "typography.body.weight",
  "typography.label.family",
  "typography.label.size",
  "typography.label.lineHeight",
  "typography.label.weight",
  "typography.caption.family",
  "typography.caption.size",
  "typography.caption.lineHeight",
  "typography.caption.weight",
  "typography.heading.family",
  "typography.heading.size",
  "typography.heading.lineHeight",
  "typography.heading.weight",
  "typography.code.family",
  "typography.code.adjustmentRatio",
  "typography.code.size",
  "typography.code.lineHeight",
  "typography.code.weight"
] as const;

export const cssVars = {
  "border.width.default": "--poodle-border-width-default",
  "border.width.focus": "--poodle-border-width-focus",
  "color.background.canvas": "--poodle-color-background-canvas",
  "color.background.surface": "--poodle-color-background-surface",
  "color.background.panel": "--poodle-color-background-panel",
  "color.background.elevated": "--poodle-color-background-elevated",
  "color.background.overlay": "--poodle-color-background-overlay",
  "color.text.primary": "--poodle-color-text-primary",
  "color.text.secondary": "--poodle-color-text-secondary",
  "color.text.inverse": "--poodle-color-text-inverse",
  "color.border.subtle": "--poodle-color-border-subtle",
  "color.border.default": "--poodle-color-border-default",
  "color.border.strong": "--poodle-color-border-strong",
  "color.accent.base": "--poodle-color-accent-base",
  "color.accent.hover": "--poodle-color-accent-hover",
  "color.accent.focusRing": "--poodle-color-accent-focusRing",
  "color.status.success": "--poodle-color-status-success",
  "color.status.warning": "--poodle-color-status-warning",
  "color.status.danger": "--poodle-color-status-danger",
  "color.icon.primary": "--poodle-color-icon-primary",
  "color.icon.muted": "--poodle-color-icon-muted",
  "elevation.surface": "--poodle-elevation-surface",
  "elevation.overlay": "--poodle-elevation-overlay",
  "elevation.dialog": "--poodle-elevation-dialog",
  "icon.size.default": "--poodle-icon-size-default",
  "icon.stroke.default": "--poodle-icon-stroke-default",
  "motion.duration.interaction": "--poodle-motion-duration-interaction",
  "motion.duration.overlay": "--poodle-motion-duration-overlay",
  "motion.easing.standard": "--poodle-motion-easing-standard",
  "motion.easing.emphasized": "--poodle-motion-easing-emphasized",
  "overlay.z.menu": "--poodle-overlay-z-menu",
  "overlay.z.dialog": "--poodle-overlay-z-dialog",
  "overlay.z.toast": "--poodle-overlay-z-toast",
  "overlay.scrimOpacity": "--poodle-overlay-scrimOpacity",
  "radius.control": "--poodle-radius-control",
  "radius.surface": "--poodle-radius-surface",
  "radius.pill": "--poodle-radius-pill",
  "size.control.height": "--poodle-size-control-height",
  "size.control.minWidth": "--poodle-size-control-minWidth",
  "size.icon.xs": "--poodle-size-icon-xs",
  "size.icon.sm": "--poodle-size-icon-sm",
  "size.icon.md": "--poodle-size-icon-md",
  "size.icon.lg": "--poodle-size-icon-lg",
  "size.icon.xl": "--poodle-size-icon-xl",
  "size.panel.header": "--poodle-size-panel-header",
  "space.stack.sm": "--poodle-space-stack-sm",
  "space.stack.md": "--poodle-space-stack-md",
  "space.stack.lg": "--poodle-space-stack-lg",
  "space.inline.sm": "--poodle-space-inline-sm",
  "space.inline.md": "--poodle-space-inline-md",
  "space.inline.lg": "--poodle-space-inline-lg",
  "space.panel.x": "--poodle-space-panel-x",
  "space.panel.y": "--poodle-space-panel-y",
  "space.control.x": "--poodle-space-control-x",
  "space.control.y": "--poodle-space-control-y",
  "state.opacity.disabled": "--poodle-state-opacity-disabled",
  "state.opacity.muted": "--poodle-state-opacity-muted",
  "typography.body.family": "--poodle-typography-body-family",
  "typography.body.size": "--poodle-typography-body-size",
  "typography.body.lineHeight": "--poodle-typography-body-lineHeight",
  "typography.body.weight": "--poodle-typography-body-weight",
  "typography.label.family": "--poodle-typography-label-family",
  "typography.label.size": "--poodle-typography-label-size",
  "typography.label.lineHeight": "--poodle-typography-label-lineHeight",
  "typography.label.weight": "--poodle-typography-label-weight",
  "typography.caption.family": "--poodle-typography-caption-family",
  "typography.caption.size": "--poodle-typography-caption-size",
  "typography.caption.lineHeight": "--poodle-typography-caption-lineHeight",
  "typography.caption.weight": "--poodle-typography-caption-weight",
  "typography.heading.family": "--poodle-typography-heading-family",
  "typography.heading.size": "--poodle-typography-heading-size",
  "typography.heading.lineHeight": "--poodle-typography-heading-lineHeight",
  "typography.heading.weight": "--poodle-typography-heading-weight",
  "typography.code.family": "--poodle-typography-code-family",
  "typography.code.adjustmentRatio": "--poodle-typography-code-adjustmentRatio",
  "typography.code.size": "--poodle-typography-code-size",
  "typography.code.lineHeight": "--poodle-typography-code-lineHeight",
  "typography.code.weight": "--poodle-typography-code-weight"
} as const;

export type TokenPath = (typeof tokenPaths)[number];
export type Tokens = typeof tokens;
