// Generated by packages/tokens/scripts/build-tokens.ts. Do not edit manually.

export const manifest = {
  "$schema": "https://www.designtokens.org/TR/2025.10/format/",
  "name": "@poodle/tokens",
  "version": "0.0.0",
  "canonicalFormat": "W3C DTCG 2025.10",
  "artifactBaseline": "Style Dictionary 4.x target shapes with bootstrap local emission script",
  "families": [
    "color",
    "typography",
    "spacing",
    "sizing",
    "radius",
    "border",
    "elevation",
    "motion",
    "density",
    "icon",
    "overlay",
    "state"
  ],
  "requiredThemes": [
    "light",
    "dark",
    "loophole-studio"
  ],
  "requiredDensityModes": [
    "compact",
    "comfortable"
  ],
  "requiredControlSizes": [
    "sm",
    "md",
    "lg"
  ],
  "artifactTargets": {
    "css": [
      "packages/tokens/artifacts/css/poodle-tokens.css",
      "packages/tokens/artifacts/css/poodle-theme-light.css",
      "packages/tokens/artifacts/css/poodle-theme-dark.css",
      "packages/tokens/artifacts/css/poodle-theme-loophole-studio.css",
      "packages/tokens/artifacts/css/poodle-density-compact.css",
      "packages/tokens/artifacts/css/poodle-density-comfortable.css"
    ],
    "ts": [
      "packages/tokens/artifacts/ts/index.ts",
      "packages/tokens/artifacts/ts/themes.ts",
      "packages/tokens/artifacts/ts/metadata.ts"
    ],
    "rust": [
      "packages/tokens/artifacts/rust/mod.rs",
      "packages/tokens/artifacts/rust/themes.rs",
      "packages/tokens/artifacts/rust/density.rs",
      "packages/tokens/artifacts/rust/metadata.rs"
    ]
  }
} as const;

export const aliases = [
  {
    "from": "semantic.color.accent.base",
    "to": "semantic.color.accent.base",
    "note": "Reserved for downstream bridges that need brand-accent mapping."
  },
  {
    "from": "semantic.size.control.height",
    "to": "semantic.size.control.height",
    "note": "Control height stays semantic so density and size overlays can override it."
  }
] as const;

export const deprecations = [
  {
    "path": "semantic.color.border.default",
    "status": "active",
    "replacement": null,
    "note": "Bootstrap file proves lifecycle metadata wiring."
  }
] as const;
