import { afterAll, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  G16_054_CANDIDATE_SCOPE_MODE,
  G18_006_CANDIDATE_SCOPE_MODE,
  LOCKSTEP_CARGO_LOCK_PATHS,
  LOCKSTEP_CARGO_MANIFEST_PATHS,
  assertCertificationScope,
  assertInstalledScope,
  emitsCertificationReceipt,
  formatInstalledRunOutput,
  readInstalledScopeMode,
  requireExactCommit,
  withDisposableGitPlant,
} from "./scope";

const plantRoots: string[] = [];

afterAll(() => {
  for (const root of plantRoots) {
    rmSync(root, { recursive: true, force: true });
  }
});

async function runGit(root: string, args: string[]): Promise<string> {
  const child = Bun.spawn(["git", "-C", root, ...args], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
    child.exited,
  ]);
  if (exitCode !== 0) {
    throw new Error(`git ${args.join(" ")} failed: ${stderr.trim()}`);
  }
  return stdout;
}

async function writeFiles(root: string, files: Record<string, string>): Promise<void> {
  for (const [path, contents] of Object.entries(files)) {
    const parts = path.split("/");
    if (parts.length > 1) {
      mkdirSync(join(root, ...parts.slice(0, -1)), { recursive: true });
    }
    await Bun.write(join(root, path), contents);
  }
}

async function commitAll(root: string, message: string): Promise<string> {
  await runGit(root, ["add", "--all"]);
  await runGit(root, ["commit", "--quiet", "-m", message]);
  return requireExactCommit(
    (await runGit(root, ["rev-parse", "HEAD"])).trim(),
    "plant commit",
  );
}

async function initPlant(): Promise<string> {
  const root = mkdtempSync(join(tmpdir(), "poodle-scope-test-"));
  plantRoots.push(root);
  await runGit(root, ["init", "--quiet"]);
  await runGit(root, ["config", "user.email", "poodle-certification@example.invalid"]);
  await runGit(root, ["config", "user.name", "Poodle Certification"]);
  return root;
}

const CANDIDATE_CARGO_PLANT_MANIFEST = "packages/contracts/tokens/Cargo.toml";
const candidateCargoPlantBase = [
  "[package]",
  'name = "poodle-tokens"',
  'version = "0.2.3"',
  'edition = "2021"',
  'license = "MIT"',
  "publish = false",
  "",
  "[dependencies]",
  'poodle-ir = { version = "0.2.3", path = "../../contracts/ir" }',
  "",
].join("\n");

const ORDINARY_CARGO_MANIFEST = "packages/gpui/node-backend/Cargo.toml";
const ORDINARY_CARGO_LOCK = "packages/gpui/node-backend/Cargo.lock";
const ordinaryCargoManifestBase = [
  "[package]",
  'name = "poodle-gpui-node-backend"',
  'version = "0.2.3"',
  'edition = "2021"',
  'license = "MIT"',
  "publish = false",
  "",
  "[dependencies]",
  'poodle-ir = { version = "0.2.3", path = "../../contracts/ir" }',
  'tinyvec = "1.12.0"',
  "",
].join("\n");
const ordinaryCargoLockBase = [
  "# This file is automatically @generated by Cargo.",
  "version = 4",
  "",
  "[[package]]",
  'name = "tinyvec"',
  'version = "1.12.0"',
  'source = "registry+https://github.com/rust-lang/crates.io-index"',
  'checksum = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"',
  "",
  "[[package]]",
  'name = "poodle-gpui-node-backend"',
  'version = "0.2.3"',
  "",
].join("\n");

const ORDINARY_JS_MANIFEST = "packages/svelte/components/package.json";
const ordinaryJsManifestBase = JSON.stringify(
  {
    name: "@inflatable-cookie/poodle-svelte",
    version: "0.3.0",
    type: "module",
    exports: {
      ".": "./dist/index.js",
      "./types": "./dist/types.js",
    },
    dependencies: {
      "@inflatable-cookie/poodle-core": "0.3.0",
      marked: "^18.0.9",
    },
  },
  null,
  2,
);

// Exact retained normalization fixture, committed locally so tests do not
// depend on the retained PR, branch, or Git object at runtime.
const ordinaryChangelogBefore = readFileSync(
  join(import.meta.dir, "fixtures/changelog-maintenance-before.md"),
  "utf8",
);
const ordinaryChangelogAfter = readFileSync(
  join(import.meta.dir, "fixtures/changelog-maintenance-after.md"),
  "utf8",
);

async function plantOrdinaryChangelogRange(
  after: string,
  extraFiles: Record<string, string> = {},
): Promise<{ root: string; base: string; head: string }> {
  const root = await initPlant();
  await writeFiles(root, { "CHANGELOG.md": ordinaryChangelogBefore });
  const base = await commitAll(root, "ordinary changelog base");
  await writeFiles(root, { "CHANGELOG.md": after, ...extraFiles });
  const head = await commitAll(root, "ordinary changelog head");
  return { root, base, head };
}

async function plantOrdinaryCargoRange(
  headFiles: Record<string, string>,
): Promise<{ root: string; base: string; head: string }> {
  const root = await initPlant();
  await writeFiles(root, {
    [ORDINARY_CARGO_MANIFEST]: `${ordinaryCargoManifestBase}\n`,
    [ORDINARY_CARGO_LOCK]: `${ordinaryCargoLockBase}\n`,
  });
  const base = await commitAll(root, "ordinary cargo base");
  await writeFiles(root, headFiles);
  const head = await commitAll(root, "ordinary cargo head");
  return { root, base, head };
}

describe("installed-package scope routing", () => {
  test("unset and ordinary resolve to ordinary; strict and candidate stay explicit", () => {
    expect(readInstalledScopeMode(undefined)).toBe("ordinary");
    expect(readInstalledScopeMode("ordinary")).toBe("ordinary");
    expect(readInstalledScopeMode("strict")).toBe("strict");
    expect(readInstalledScopeMode(G16_054_CANDIDATE_SCOPE_MODE)).toBe(
      G16_054_CANDIDATE_SCOPE_MODE,
    );
    expect(readInstalledScopeMode(G18_006_CANDIDATE_SCOPE_MODE)).toBe(
      G18_006_CANDIDATE_SCOPE_MODE,
    );
    expect(emitsCertificationReceipt("ordinary")).toBe(false);
    expect(emitsCertificationReceipt("strict")).toBe(true);
    expect(emitsCertificationReceipt(G16_054_CANDIDATE_SCOPE_MODE)).toBe(true);
    expect(emitsCertificationReceipt(G18_006_CANDIDATE_SCOPE_MODE)).toBe(true);
  });

  test("unknown mode rejects instead of becoming ordinary", () => {
    expect(() => readInstalledScopeMode("typo")).toThrow(
      /must be ordinary, strict, or g16\.054-candidate, g18\.006-candidate: typo/,
    );
    expect(() => readInstalledScopeMode("strict ")).toThrow(
      /must be ordinary, strict, or g16\.054-candidate, g18\.006-candidate/,
    );
  });

  test("ordinary output cannot print a certification receipt hash", () => {
    const ordinary = formatInstalledRunOutput({
      mode: "ordinary",
      sourceCommit: "a".repeat(40),
      falsificationReceipts: [],
      receiptSha256: "should-not-leak",
      receipt: { kind: "poodle-installed-web-distribution" },
    });
    expect(ordinary).not.toContain("receiptSha256");
    expect(ordinary).not.toContain("poodle-installed-web-distribution");
    expect(ordinary).toContain('"mode": "ordinary"');
    const strict = formatInstalledRunOutput({
      mode: "strict",
      sourceCommit: "a".repeat(40),
      falsificationReceipts: [],
      receiptSha256: "abc123",
      receipt: { kind: "poodle-installed-web-distribution" },
    });
    expect(strict).toContain("receiptSha256");
    expect(strict).toContain("abc123");
  });

  test("ordinary empty range passes and is not certification", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const commit = await commitAll(root, "empty range base");
    const proof = await assertInstalledScope(root, commit, commit, "ordinary");
    expect(proof.mode).toBe("ordinary");
    expect(proof.changedPaths).toEqual([]);
    expect(emitsCertificationReceipt(proof.mode)).toBe(false);
  });

  test("ordinary feature source path passes", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const base = await commitAll(root, "feature base");
    await writeFiles(root, {
      "packages/svelte/components/src/Tabs.svelte": "<div>tabs</div>\n",
    });
    const head = await commitAll(root, "ordinary feature");
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.changedPaths).toEqual(["packages/svelte/components/src/Tabs.svelte"]);
    expect(emitsCertificationReceipt(proof.mode)).toBe(false);
  });

  test("ordinary allowlist-shaped paths still do not become certification", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const base = await commitAll(root, "allowlist base");
    await writeFiles(root, { "PAPERCUTS.md": "friction\n" });
    const head = await commitAll(root, "allowlist-shaped ordinary");
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.mode).toBe("ordinary");
    expect(proof.changedPaths).toEqual(["PAPERCUTS.md"]);
    expect(emitsCertificationReceipt(proof.mode)).toBe(false);
  });

  test("ordinary workflow, release, version, and registry paths reject before build", async () => {
    const cases = [
      [".github/workflows/release.yml", "workflow"],
      ["CHANGELOG.md", "release"],
      ["packages/core/package.json", "version"],
      [".npmrc", "registry"],
      ["scripts/publish/release.ts", "release"],
    ] as const;
    for (const [path, surface] of cases) {
      const root = await initPlant();
      await writeFiles(root, { "README.md": "base\n" });
      const base = await commitAll(root, "forbidden base");
      await writeFiles(root, { [path]: "planted\n" });
      const head = await commitAll(root, "forbidden mutation");
      await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
        new RegExp(`certification scope rejected forbidden ${surface} surface: ${path}`),
      );
    }
  });

  test("ordinary admits the bound changelog normalization with one execution log", async () => {
    const executionLog = "docs/logs/2026-09/20260910-g99-999-changelog-maintenance.md";
    const { root, base, head } = await plantOrdinaryChangelogRange(
      ordinaryChangelogAfter,
      { [executionLog]: "# Changelog maintenance\n" },
    );
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.changedPaths).toEqual(["CHANGELOG.md", executionLog]);
  });

  test("ordinary changelog maintenance rejects semantic inventory mutations", async () => {
    const executionLog = {
      "docs/logs/2026-09/20260910-g99-999-changelog-maintenance.md": "# Changelog maintenance\n",
    };
    const plants = {
      version: ordinaryChangelogAfter.replace("## [0.3.0]", "## [0.3.1]"),
      date: ordinaryChangelogAfter.replace("2026-09-05", "2026-09-06"),
      link: ordinaryChangelogAfter.replace(
        "docs/release-notes/0.3.0.md",
        "docs/release-notes/changed.md",
      ),
      entry: ordinaryChangelogAfter.replace("shared motion policy", "changed motion policy"),
      unreleased: ordinaryChangelogAfter.replace(
        "## [Unreleased]\n",
        "## [Unreleased]\n\n- A real unreleased entry.\n",
      ),
      removedRelease: ordinaryChangelogAfter.replace(
        /\n## \[0\.2\.2\][\s\S]*?(?=\n## \[0\.2\.0\])/, "",
      ),
    };
    for (const [kind, changelog] of Object.entries(plants)) {
      const { root, base, head } = await plantOrdinaryChangelogRange(changelog, executionLog);
      await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
        "certification scope rejected forbidden release surface: CHANGELOG.md",
      );
    }
  });

  test("ordinary changelog maintenance rejects missing logs, mixed ranges, and ambiguity", async () => {
    const cases = [
      { after: ordinaryChangelogAfter, extraFiles: {} },
      {
        after: ordinaryChangelogAfter,
        extraFiles: {
          "docs/logs/2026-09/20260910-g99-999-changelog-maintenance.md": "# Log\n",
          "packages/core/src/release-stowaway.ts": "export {};\n",
        },
      },
      {
        after: ordinaryChangelogAfter.replace(
          "### Added\n",
          "#### Unsupported nested release heading\n",
        ),
        extraFiles: {
          "docs/logs/2026-09/20260910-g99-999-changelog-maintenance.md": "# Log\n",
        },
      },
    ];
    for (const { after, extraFiles } of cases) {
      const { root, base, head } = await plantOrdinaryChangelogRange(after, extraFiles);
      await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
        "certification scope rejected forbidden release surface: CHANGELOG.md",
      );
    }
  });

  test("ordinary dependency feature and lock refresh is not a version surface", async () => {
    const { root, base, head } = await plantOrdinaryCargoRange({
      [ORDINARY_CARGO_MANIFEST]: ordinaryCargoManifestBase.replace(
        'tinyvec = "1.12.0"',
        'tinyvec = { version = "1.13.0", features = ["std"] }',
      ) + "\n",
      [ORDINARY_CARGO_LOCK]: ordinaryCargoLockBase.replaceAll("1.12.0", "1.13.0") + "\n",
    });
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.mode).toBe("ordinary");
    expect(proof.changedPaths).toEqual([ORDINARY_CARGO_LOCK, ORDINARY_CARGO_MANIFEST]);
    expect(emitsCertificationReceipt(proof.mode)).toBe(false);
  });

  test("ordinary [package] version mutation stays a version surface", async () => {
    const { root, base, head } = await plantOrdinaryCargoRange({
      [ORDINARY_CARGO_MANIFEST]: ordinaryCargoManifestBase.replace(
        'version = "0.2.3"',
        'version = "0.3.0"',
      ) + "\n",
    });
    await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
      `certification scope rejected forbidden version surface: ${ORDINARY_CARGO_MANIFEST}`,
    );
  });

  test("ordinary [workspace.package] version mutation stays a version surface", async () => {
    const root = await initPlant();
    await writeFiles(root, {
      "Cargo.toml": [
        "[workspace]",
        'members = ["packages/gpui/node-backend"]',
        "",
        "[workspace.package]",
        'version = "0.2.3"',
        "",
      ].join("\n"),
    });
    const base = await commitAll(root, "workspace version base");
    await writeFiles(root, {
      "Cargo.toml": [
        "[workspace]",
        'members = ["packages/gpui/node-backend"]',
        "",
        "[workspace.package]",
        'version = "0.3.0"',
        "",
      ].join("\n"),
    });
    const head = await commitAll(root, "workspace version mutation");
    await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
      "certification scope rejected forbidden version surface: Cargo.toml",
    );
  });

  test("ordinary inline dependency version is classified by owning section", async () => {
    const { root, base, head } = await plantOrdinaryCargoRange({
      [ORDINARY_CARGO_MANIFEST]: ordinaryCargoManifestBase.replace(
        'poodle-ir = { version = "0.2.3", path = "../../contracts/ir" }',
        'poodle-ir = { version = "0.3.0", features = ["std"], path = "../../contracts/ir" }',
      ) + "\n",
    });
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.changedPaths).toEqual([ORDINARY_CARGO_MANIFEST]);
    expect(emitsCertificationReceipt(proof.mode)).toBe(false);
  });

  test("ordinary Cargo.lock resolution is not a version surface", async () => {
    const { root, base, head } = await plantOrdinaryCargoRange({
      [ORDINARY_CARGO_LOCK]: ordinaryCargoLockBase.replaceAll("1.12.0", "1.13.0") + "\n",
    });
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.changedPaths).toEqual([ORDINARY_CARGO_LOCK]);
  });

  test("ordinary Cargo publication, registry, source, patch, and replace still reject", async () => {
    const plants = {
      publish: ordinaryCargoManifestBase.replace("publish = false", "publish = true"),
      registry: ordinaryCargoManifestBase.replace(
        'license = "MIT"',
        'registry = "https://registry.example.invalid"',
      ),
      source: ordinaryCargoManifestBase.replace(
        'tinyvec = "1.12.0"',
        'tinyvec = { version = "1.12.0", source = "registry+https://evil.example.invalid" }',
      ),
      patch: `${ordinaryCargoManifestBase}\n[patch.crates-io]\ntinyvec = { path = "vendor/tinyvec" }\n`,
      replace: `${ordinaryCargoManifestBase}\n[replace]\n"tinyvec:1.12.0" = { path = "vendor/tinyvec" }\n`,
    };
    for (const planted of Object.values(plants)) {
      const { root, base, head } = await plantOrdinaryCargoRange({
        [ORDINARY_CARGO_MANIFEST]: planted.endsWith("\n") ? planted : `${planted}\n`,
      });
      await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
        new RegExp(
          `certification scope rejected forbidden registry surface: ${ORDINARY_CARGO_MANIFEST}`,
        ),
      );
    }
  });

  test("ordinary exact pinned dependency and export additions are not a version surface", async () => {
    const root = await initPlant();
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${ordinaryJsManifestBase}\n` });
    const base = await commitAll(root, "ordinary js base");
    const added = JSON.parse(ordinaryJsManifestBase) as Record<string, unknown>;
    (added["dependencies"] as Record<string, string>)["@codemirror/state"] = "6.7.4";
    (added["dependencies"] as Record<string, string>)["@codemirror/view"] = "6.43.11";
    (added["exports"] as Record<string, unknown>)["./editor"] = {
      types: "./dist/editor.d.ts",
      browser: "./dist/editor.client.js",
      default: "./dist/editor.server.js",
    };
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${JSON.stringify(added, null, 2)}\n` });
    const head = await commitAll(root, "ordinary js editor isolation");
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.mode).toBe("ordinary");
    expect(proof.changedPaths).toEqual([ORDINARY_JS_MANIFEST]);
    expect(emitsCertificationReceipt(proof.mode)).toBe(false);
  });

  test("ordinary dependency refresh and manifest reformatting are not a version surface", async () => {
    const root = await initPlant();
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${ordinaryJsManifestBase}\n` });
    const base = await commitAll(root, "ordinary js base");
    const refreshed = JSON.parse(ordinaryJsManifestBase) as Record<string, unknown>;
    (refreshed["dependencies"] as Record<string, string>)["marked"] = "^18.1.0";
    const reformatted: Record<string, unknown> = {};
    for (const key of Object.keys(refreshed).sort().reverse()) {
      reformatted[key] = refreshed[key];
    }
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${JSON.stringify(reformatted)}\n` });
    const head = await commitAll(root, "ordinary js refresh");
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.mode).toBe("ordinary");
    expect(proof.changedPaths).toEqual([ORDINARY_JS_MANIFEST]);
  });

  test("ordinary JS version and name mutations stay a version surface", async () => {
    for (const mutate of [
      (manifest: Record<string, unknown>) => {
        manifest["version"] = "0.4.0";
      },
      (manifest: Record<string, unknown>) => {
        manifest["name"] = "@inflatable-cookie/poodle-evil";
      },
    ]) {
      const root = await initPlant();
      await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${ordinaryJsManifestBase}\n` });
      const base = await commitAll(root, "ordinary js base");
      const mutated = JSON.parse(ordinaryJsManifestBase) as Record<string, unknown>;
      mutate(mutated);
      await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${JSON.stringify(mutated, null, 2)}\n` });
      const head = await commitAll(root, "ordinary js mutation");
      await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
        `certification scope rejected forbidden version surface: ${ORDINARY_JS_MANIFEST}`,
      );
    }
  });

  test("ordinary JS publication and registry mutations stay a registry surface", async () => {
    const plants = {
      unprivate: (manifest: Record<string, unknown>) => {
        manifest["private"] = false;
      },
      publishAccess: (manifest: Record<string, unknown>) => {
        manifest["publishConfig"] = { access: "public" };
      },
      registryTransport: (manifest: Record<string, unknown>) => {
        (manifest["publishConfig"] as Record<string, string>)["registry"] =
          "https://registry.example.invalid";
      },
    } as const;
    for (const [kind, mutate] of Object.entries(plants)) {
      const root = await initPlant();
      const withPrivate = JSON.parse(ordinaryJsManifestBase) as Record<string, unknown>;
      withPrivate["private"] = true;
      withPrivate["publishConfig"] = { access: "restricted" };
      await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${JSON.stringify(withPrivate, null, 2)}\n` });
      const base = await commitAll(root, `ordinary js ${kind} base`);
      const mutated = JSON.parse(JSON.stringify(withPrivate)) as Record<string, unknown>;
      mutate(mutated);
      await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${JSON.stringify(mutated, null, 2)}\n` });
      const head = await commitAll(root, `ordinary js ${kind} plant`);
      await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
        `certification scope rejected forbidden registry surface: ${ORDINARY_JS_MANIFEST}`,
      );
    }
  });

  test("ordinary JS added, deleted, and unparsable manifests fail closed", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const base = await commitAll(root, "ordinary js closed base");
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${ordinaryJsManifestBase}\n` });
    const added = await commitAll(root, "ordinary js manifest added");
    await expect(assertInstalledScope(root, base, added, "ordinary")).rejects.toThrow(
      `certification scope rejected forbidden version surface: ${ORDINARY_JS_MANIFEST}`,
    );
    await writeFiles(root, { "README.md": "base\nmore\n" });
    const deletedBase = await commitAll(root, "ordinary js present base");
    await runGit(root, ["rm", "--quiet", ORDINARY_JS_MANIFEST]);
    const deleted = await commitAll(root, "ordinary js manifest deleted");
    await expect(assertInstalledScope(root, deletedBase, deleted, "ordinary")).rejects.toThrow(
      `certification scope rejected forbidden version surface: ${ORDINARY_JS_MANIFEST}`,
    );
    await writeFiles(root, {
      "README.md": "base\nmore\nagain\n",
      [ORDINARY_JS_MANIFEST]: `${ordinaryJsManifestBase}\n`,
    });
    const unparsableBase = await commitAll(root, "ordinary js parsable base");
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: "planted\n" });
    const unparsable = await commitAll(root, "ordinary js unparsable");
    await expect(assertInstalledScope(root, unparsableBase, unparsable, "ordinary")).rejects.toThrow(
      `certification scope rejected forbidden version surface: ${ORDINARY_JS_MANIFEST}`,
    );
  });

  test("strict still path-rejects a JS dependency-only edit", async () => {
    const root = await initPlant();
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${ordinaryJsManifestBase}\n` });
    const base = await commitAll(root, "strict js base");
    const edited = JSON.parse(ordinaryJsManifestBase) as Record<string, unknown>;
    (edited["dependencies"] as Record<string, string>)["marked"] = "^18.1.0";
    await writeFiles(root, { [ORDINARY_JS_MANIFEST]: `${JSON.stringify(edited, null, 2)}\n` });
    const head = await commitAll(root, "strict js edit");
    await expect(assertCertificationScope(root, base, head, "strict")).rejects.toThrow(
      `certification scope rejected forbidden version surface: ${ORDINARY_JS_MANIFEST}`,
    );
  });

  test("strict still path-rejects a Cargo dependency-only edit", async () => {
    const { root, base, head } = await plantOrdinaryCargoRange({
      [ORDINARY_CARGO_MANIFEST]: ordinaryCargoManifestBase.replace(
        'tinyvec = "1.12.0"',
        'tinyvec = { version = "1.13.0", features = ["std"] }',
      ) + "\n",
    });
    await expect(assertCertificationScope(root, base, head, "strict")).rejects.toThrow(
      `certification scope rejected forbidden version surface: ${ORDINARY_CARGO_MANIFEST}`,
    );
  });

  test("strict empty range still fails", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const commit = await commitAll(root, "strict empty");
    await expect(assertCertificationScope(root, commit, commit, "strict")).rejects.toThrow(
      "certification scope found no changed paths",
    );
  });

  test("strict keeps the g16.059 allowlist", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const base = await commitAll(root, "strict base");
    await writeFiles(root, {
      "packages/svelte/components/src/Tabs.svelte": "<div>tabs</div>\n",
    });
    const head = await commitAll(root, "strict feature");
    await expect(assertCertificationScope(root, base, head, "strict")).rejects.toThrow(
      "certification scope rejected paths outside writable allowlist: packages/svelte/components/src/Tabs.svelte",
    );
  });

  test("strict accepts a g16.059 writable path", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const base = await commitAll(root, "strict writable base");
    await writeFiles(root, { "PAPERCUTS.md": "friction\n" });
    const head = await commitAll(root, "strict writable");
    const proof = await assertCertificationScope(root, base, head, "strict");
    expect(proof.mode).toBe("strict");
    expect(proof.changedPaths).toEqual(["PAPERCUTS.md"]);
  });

  test("candidate rejects an unauthorized source path", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const base = await commitAll(root, "candidate base");
    await writeFiles(root, { "packages/core/src/unauthorized.ts": "export {}\n" });
    const head = await commitAll(root, "candidate unauthorized");
    await expect(
      assertCertificationScope(root, base, head, G16_054_CANDIDATE_SCOPE_MODE),
    ).rejects.toThrow(
      "certification scope rejected paths outside writable allowlist: packages/core/src/unauthorized.ts",
    );
  });

  test("candidate rejects Cargo publish, registry, and retargeted requirement content", async () => {
    const plants = {
      publish: candidateCargoPlantBase.replace("publish = false", "publish = true"),
      registry: candidateCargoPlantBase.replace(
        'license = "MIT"',
        'registry = "https://registry.example.invalid"',
      ),
      retargeted: candidateCargoPlantBase.replace(
        'poodle-ir = { version = "0.2.3", path = "../../contracts/ir" }',
        'poodle-ir = { version = "0.3.0", path = "../../contracts/evil" }',
      ),
    };
    for (const [kind, planted] of Object.entries(plants)) {
      const root = await initPlant();
      await writeFiles(root, { [CANDIDATE_CARGO_PLANT_MANIFEST]: `${candidateCargoPlantBase}\n` });
      const base = await commitAll(root, `cargo ${kind} base`);
      await writeFiles(root, { [CANDIDATE_CARGO_PLANT_MANIFEST]: `${planted}\n` });
      const head = await commitAll(root, `cargo ${kind} plant`);
      await expect(
        assertCertificationScope(root, base, head, G16_054_CANDIDATE_SCOPE_MODE),
      ).rejects.toThrow(/candidate scope rejected/);
    }
  });

  test("candidate rejects the evidence head as the certified source", async () => {
    const root = await initPlant();
    await writeFiles(root, { "docs/release-notes/README.md": "release-note index\n" });
    const base = await commitAll(root, "branch base");
    await writeFiles(root, {
      "docs/release-notes/README.md": "release-note index\ncandidate tree delta\n",
    });
    await commitAll(root, "candidate tree");
    await writeFiles(root, {
      "docs/release-notes/README.md":
        "release-note index\ncandidate tree delta\nevidence-only delta\n",
    });
    const evidence = await commitAll(root, "candidate evidence");
    await expect(
      assertCertificationScope(root, base, evidence, G16_054_CANDIDATE_SCOPE_MODE),
    ).rejects.toThrow(
      /candidate scope requires the certified source to be the direct one-commit child/,
    );
  });

  test("disposable plants restore by deleting the committed plant root", async () => {
    let observed = "";
    await withDisposableGitPlant(async (root) => {
      observed = root;
      await runGit(root, ["init", "--quiet"]);
    });
    expect(observed.length).toBeGreaterThan(0);
    expect(plantRoots.includes(observed)).toBe(false);
  });
});

const CLOSED_CANDIDATE_EVIDENCE = "docs/evidence/nucleus/nucleus-parity-manifest.json";
const CLOSED_CANDIDATE_STAMP = "packages/codegen/generated/json/index.json";

function closedCandidateChangelog(version: string): string {
  return [
    "# Changelog",
    "",
    "Notable changes to Poodle are recorded here.",
    "",
    "## [Unreleased]",
    "",
    `## [${version}] - 2026-09-12`,
    "",
    "### Added",
    "",
    "- Planted candidate entry.",
    "",
    "[Unreleased]: https://github.com/inflatable-cookie/poodle/commits/main",
    `[${version}]: docs/release-notes/${version}.md`,
    "",
  ].join("\n");
}

function closedCandidateFiles(version: string): Record<string, string> {
  const files: Record<string, string> = {
    "packages/core/package.json": `${JSON.stringify(
      { name: "@inflatable-cookie/poodle-core", version, type: "module" },
      null,
      2,
    )}\n`,
    "packages/svelte/components/package.json": `${JSON.stringify(
      {
        name: "@inflatable-cookie/poodle-svelte",
        version,
        dependencies: { "@inflatable-cookie/poodle-core": version },
      },
      null,
      2,
    )}\n`,
    "packages/react/components/package.json": `${JSON.stringify(
      {
        name: "@inflatable-cookie/poodle-react",
        version,
        private: true,
        dependencies: { "@inflatable-cookie/poodle-core": version },
      },
      null,
      2,
    )}\n`,
    "bun.lock": `lock ${version}\n`,
    "CHANGELOG.md": closedCandidateChangelog(version),
    "docs/release-notes/README.md": `# Release notes\n\n- [${version}]\n`,
    [CLOSED_CANDIDATE_STAMP]: `{"generated":{"generator":"poodle-codegen ${version}"}}\n`,
    [CLOSED_CANDIDATE_EVIDENCE]: `${JSON.stringify(
      {
        schema: "poodle.g16.062-nucleus-parity-manifest.v1",
        resolution: { source_commit: "0".repeat(40) },
      },
      null,
      2,
    )}\n`,
  };
  for (const path of LOCKSTEP_CARGO_MANIFEST_PATHS) {
    const dependency =
      path === "packages/contracts/tokens/Cargo.toml"
        ? ['poodle-ir = { version = "' + version + '", path = "../../contracts/ir" }', ""]
        : [];
    files[path] = [
      "[package]",
      'name = "planted"',
      `version = "${version}"`,
      'edition = "2021"',
      "publish = false",
      "",
      ...(dependency.length > 0 ? ["[dependencies]", ...dependency] : []),
    ].join("\n");
  }
  for (const path of LOCKSTEP_CARGO_LOCK_PATHS) {
    files[path] = `# planted ${version}\nversion = 4\n`;
  }
  return files;
}

type ClosedCandidatePlant = {
  mutateCandidate?: (files: Record<string, string>) => void;
  evidenceSourceCommit?: (frozen: string, base: string) => string;
  afterEvidence?: Record<string, string>;
};

async function plantClosedCandidate(plant: ClosedCandidatePlant = {}): Promise<{
  root: string;
  base: string;
  frozen: string;
  head: string;
}> {
  const root = await initPlant();
  await writeFiles(root, closedCandidateFiles("0.3.0"));
  const base = await commitAll(root, "closed candidate base");
  const candidateFiles = closedCandidateFiles("0.4.0");
  candidateFiles["docs/release-notes/0.4.0.md"] = "# Poodle 0.4.0\n";
  plant.mutateCandidate?.(candidateFiles);
  await writeFiles(root, candidateFiles);
  const frozen = await commitAll(root, "closed candidate frozen release inputs");
  const recorded = plant.evidenceSourceCommit
    ? plant.evidenceSourceCommit(frozen, base)
    : frozen;
  await writeFiles(root, {
    [CLOSED_CANDIDATE_EVIDENCE]: `${JSON.stringify(
      {
        schema: "poodle.g16.062-nucleus-parity-manifest.v1",
        resolution: { source_commit: recorded },
      },
      null,
      2,
    )}\n`,
  });
  const evidenceHead = await commitAll(root, "closed candidate evidence");
  if (!plant.afterEvidence) return { root, base, frozen, head: evidenceHead };
  await writeFiles(root, plant.afterEvidence);
  const head = await commitAll(root, "closed candidate extra");
  return { root, base, frozen, head };
}

describe("closed 0.4.0 candidate scope admission", () => {
  test("ordinary CI admits the complete closed candidate without a receipt", async () => {
    const { root, base, head } = await plantClosedCandidate();
    const proof = await assertInstalledScope(root, base, head, "ordinary");
    expect(proof.mode).toBe("ordinary");
    expect(emitsCertificationReceipt(proof.mode)).toBe(false);
    expect(proof.changedPaths).toContain("packages/render/Cargo.toml");
    expect(proof.changedPaths).toContain("docs/release-notes/0.4.0.md");
    expect(proof.changedPaths).toContain(CLOSED_CANDIDATE_EVIDENCE);
  });

  test("explicit g18.006 mode certifies the same closed candidate", async () => {
    const { root, base, head } = await plantClosedCandidate();
    const proof = await assertCertificationScope(
      root,
      base,
      head,
      G18_006_CANDIDATE_SCOPE_MODE,
    );
    expect(proof.mode).toBe(G18_006_CANDIDATE_SCOPE_MODE);
    expect(emitsCertificationReceipt(proof.mode)).toBe(true);
  });

  test("partial and wrong-version candidates fail before build or pack", async () => {
    const partial = await plantClosedCandidate({
      mutateCandidate: (files) => {
        delete files["packages/gpui/preview/Cargo.toml"];
        delete files["packages/render/Cargo.toml"];
      },
    });
    await expect(
      assertInstalledScope(partial.root, partial.base, partial.head, "ordinary"),
    ).rejects.toThrow(/certification scope rejected forbidden/);
    await expect(
      assertCertificationScope(
        partial.root,
        partial.base,
        partial.head,
        G18_006_CANDIDATE_SCOPE_MODE,
      ),
    ).rejects.toThrow(/requires the complete 0\.4\.0 release-input set; missing/);

    const wrongVersion = await plantClosedCandidate({
      mutateCandidate: (files) => {
        files["packages/render/Cargo.toml"] = (
          files["packages/render/Cargo.toml"] as string
        ).replace('version = "0.4.0"', 'version = "0.3.1"');
      },
    });
    await expect(
      assertCertificationScope(
        wrongVersion.root,
        wrongVersion.base,
        wrongVersion.head,
        G18_006_CANDIDATE_SCOPE_MODE,
      ),
    ).rejects.toThrow(/candidate scope rejected unauthorized Cargo manifest change/);
  });

  test("closed candidate scope rejects arbitrary source and transport surfaces", async () => {
    const plants = {
      "packages/core/src/unauthorized.ts": "export {};\n",
      "test/package-install/scope.ts": "export {};\n",
      ".github/workflows/release.yml": "name: planted\n",
      ".npmrc": "registry=https://registry.example.invalid\n",
      "scripts/publish/release.ts": "export {};\n",
    };
    for (const [path, contents] of Object.entries(plants)) {
      const { root, base, head } = await plantClosedCandidate({
        afterEvidence: { [path]: contents },
      });
      await expect(
        assertCertificationScope(root, base, head, G18_006_CANDIDATE_SCOPE_MODE),
      ).rejects.toThrow(/certification scope rejected/);
    }
  });

  test("closed candidate scope rejects React admission and Cargo retargeting", async () => {
    const react = await plantClosedCandidate({
      mutateCandidate: (files) => {
        const manifest = JSON.parse(files["packages/react/components/package.json"] as string);
        manifest.private = false;
        files["packages/react/components/package.json"] = `${JSON.stringify(manifest, null, 2)}\n`;
      },
    });
    await expect(
      assertCertificationScope(react.root, react.base, react.head, G18_006_CANDIDATE_SCOPE_MODE),
    ).rejects.toThrow(/candidate scope rejected/);

    const retargeted = await plantClosedCandidate({
      mutateCandidate: (files) => {
        files["packages/contracts/tokens/Cargo.toml"] = (
          files["packages/contracts/tokens/Cargo.toml"] as string
        ).replace('path = "../../contracts/ir"', 'path = "../../contracts/evil"');
      },
    });
    await expect(
      assertCertificationScope(
        retargeted.root,
        retargeted.base,
        retargeted.head,
        G18_006_CANDIDATE_SCOPE_MODE,
      ),
    ).rejects.toThrow(/candidate scope rejected unauthorized Cargo manifest change/);
  });

  test("closed candidate scope rejects stale or arbitrary internal JS dependencies", async () => {
    const mutateDependency = (
      manifestPath: string,
      specifier: string | null,
    ) => (files: Record<string, string>) => {
      const manifest = JSON.parse(files[manifestPath] as string);
      if (specifier === null) {
        delete manifest.dependencies["@inflatable-cookie/poodle-core"];
      } else {
        manifest.dependencies["@inflatable-cookie/poodle-core"] = specifier;
      }
      files[manifestPath] = `${JSON.stringify(manifest, null, 2)}\n`;
    };
    const plants = {
      stale: mutateDependency("packages/svelte/components/package.json", "0.3.0"),
      arbitrary: mutateDependency("packages/react/components/package.json", "^0.4.0"),
      removed: mutateDependency("packages/svelte/components/package.json", null),
    };
    for (const mutateCandidate of Object.values(plants)) {
      const { root, base, head } = await plantClosedCandidate({ mutateCandidate });
      await expect(
        assertCertificationScope(root, base, head, G18_006_CANDIDATE_SCOPE_MODE),
      ).rejects.toThrow(/internal JS dependency/);
    }
  });

  test("closed candidate scope rejects an unchanged stale Cargo requirement", async () => {
    const { root, base, head } = await plantClosedCandidate({
      mutateCandidate: (files) => {
        files["packages/contracts/tokens/Cargo.toml"] = (
          files["packages/contracts/tokens/Cargo.toml"] as string
        ).replace(
          'poodle-ir = { version = "0.4.0", path = "../../contracts/ir" }',
          'poodle-ir = { version = "0.3.0", path = "../../contracts/ir" }',
        );
      },
    });
    await expect(
      assertCertificationScope(root, base, head, G18_006_CANDIDATE_SCOPE_MODE),
    ).rejects.toThrow(
      /requires intra-repository Cargo requirement poodle-ir in packages\/contracts\/tokens\/Cargo\.toml to move 0\.3\.0 -> 0\.4\.0, found 0\.3\.0 -> 0\.3\.0/,
    );
  });

  test("closed candidate scope rejects hidden or later release-input drift", async () => {
    const driftedManifest = (
      closedCandidateFiles("0.4.0")["packages/render/Cargo.toml"] as string
    ).replace('version = "0.4.0"', 'version = "0.4.1"');
    const drift = await plantClosedCandidate({
      afterEvidence: { "packages/render/Cargo.toml": driftedManifest },
    });
    await expect(
      assertCertificationScope(drift.root, drift.base, drift.head, G18_006_CANDIDATE_SCOPE_MODE),
    ).rejects.toThrow(
      /requires exactly one frozen 0\.4\.0 release-input commit; found 2/,
    );
  });

  test("closed candidate scope rejects evidence bound to another commit", async () => {
    const misbound = await plantClosedCandidate({
      evidenceSourceCommit: (_frozen, base) => base,
    });
    await expect(
      assertCertificationScope(
        misbound.root,
        misbound.base,
        misbound.head,
        G18_006_CANDIDATE_SCOPE_MODE,
      ),
    ).rejects.toThrow(/bound to .* instead of the frozen release-input commit/);
  });

  test("ordinary CI refuses a lone version bump instead of promoting it", async () => {
    const root = await initPlant();
    await writeFiles(root, { "packages/core/package.json": '{\n  "version": "0.3.0"\n}\n' });
    const base = await commitAll(root, "lone bump base");
    await writeFiles(root, { "packages/core/package.json": '{\n  "version": "0.4.0"\n}\n' });
    const head = await commitAll(root, "lone bump head");
    await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
      "certification scope rejected forbidden version surface: packages/core/package.json",
    );
  });

  test("ordinary CI refuses a lone release-note change instead of promoting it", async () => {
    const root = await initPlant();
    await writeFiles(root, { "README.md": "base\n" });
    const base = await commitAll(root, "lone release note base");
    await writeFiles(root, { "docs/release-notes/0.4.0.md": "# Poodle 0.4.0\n" });
    const head = await commitAll(root, "lone release note head");
    await expect(assertInstalledScope(root, base, head, "ordinary")).rejects.toThrow(
      /rejected a partial release-note change without the closed g18\.006-candidate candidate/,
    );
  });

  test("g16.054 still requires its own 0.2.3 source identity", async () => {
    const root = await initPlant();
    await writeFiles(root, { "packages/core/package.json": '{\n  "version": "0.3.0"\n}\n' });
    const base = await commitAll(root, "g16 candidate base");
    await writeFiles(root, { "packages/core/package.json": '{\n  "version": "0.4.0"\n}\n' });
    const head = await commitAll(root, "g16 candidate head");
    await expect(
      assertCertificationScope(root, base, head, G16_054_CANDIDATE_SCOPE_MODE),
    ).rejects.toThrow(/candidate scope requires packages\/core\/package\.json/);
  });
});
