//! The pure emission core: target abstraction, generated header,
//! deterministic ordering, and in-memory rendering.
//!
//! Nothing in this module touches the filesystem. Rendering is a pure
//! function of `(model, source_path, target)`, so two consecutive runs of
//! the same inputs are byte-identical by construction and the check/write
//! split below can be a separate concern.

use poodle_ir::{IrModel, IR_SCHEMA_VERSION};

use crate::error::Result;
use crate::GENERATOR_VERSION;

/// One artifact a target renders — path relative to the target's output
/// root, contents in full.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Output-root-relative path, `/`-separated, e.g. `badge.ts`.
    pub path: String,
    /// Complete file contents, including the generated header.
    pub contents: String,
}

impl GeneratedFile {
    /// Builds a generated file.
    pub fn new(path: impl Into<String>, contents: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            contents: contents.into(),
        }
    }
}

/// A code-generation target — one output family over the same model.
///
/// This card ships exactly one target (TypeScript); JSON schema, registry,
/// conformance-vector, and docs-fragment targets are a follow-up card. The
/// abstraction exists now because the machinery — header, ordering, byte
/// comparison, orphan scan — is target-independent, and that machinery is
/// the risk this card retires.
pub trait EmitTarget {
    /// Stable target id, e.g. `typescript`.
    fn id(&self) -> &'static str;

    /// Subdirectory of the committed output root this target owns, e.g.
    /// `ts`. Check mode scans exactly this root for stale orphans.
    fn output_root(&self) -> &'static str;

    /// Renders the model into files. Pure: no I/O, no environment access.
    /// `source_path` is the repo-relative authored source path carried into
    /// the header (`IR-07`).
    fn render(&self, model: &IrModel, source_path: &str) -> Result<Vec<GeneratedFile>>;
}

/// The generated header (`IR-07`): authored source path, IR schema version,
/// generator version. No timestamp, no absolute path, no machine or user
/// identifier — the nondeterminism this card exists to exclude. A pure
/// function of its argument, so the same source always yields the same
/// header.
pub fn header(source_path: &str) -> String {
    format!(
        "// Generated by poodle-codegen {GENERATOR_VERSION}. Do not edit manually.\n\
         // Source: {source_path}\n\
         // IR schema version: {IR_SCHEMA_VERSION}\n\
         // Regenerate with `effigy ir:build`; drift is gated by `effigy ir:check`.\n"
    )
}

/// Header for machine-interface artifacts (spec 064 mechanism 1). Same
/// determinism rules as [`header`], but stamps the machine-interface schema
/// version instead of the IR schema — these files are not IR output.
pub fn machine_header(source_path: &str, schema_version: u32) -> String {
    format!(
        "// Generated by poodle-codegen {GENERATOR_VERSION}. Do not edit manually.\n\
         // Source: {source_path}\n\
         // Machine interface schema version: {schema_version}\n\
         // Regenerate with `effigy ir:build`; drift is gated by `effigy ir:check`.\n"
    )
}

/// Renders the model through one target, validating nothing (the caller
/// validates; see [`crate::model::load_and_validate`]) but never panicking —
/// an unresolvable reference is a [`CodegenError`], not a panic.
pub fn generate(
    model: &IrModel,
    source_path: &str,
    target: &dyn EmitTarget,
) -> Result<Vec<GeneratedFile>> {
    target.render(model, source_path)
}

/// Stable ordering for top-level collections: by id. Model-array order is
/// not trusted for output; a reorder in the fixture must not reorder the
/// artifact.
pub(crate) fn sort_by_id<T>(items: &mut [T], id: impl Fn(&T) -> &str) {
    items.sort_by(|a, b| id(a).cmp(id(b)));
}
