//! Component registry — mirrors the Svelte preview's component-registry.ts.
//!
//! Lists every primitive and composite component with display name and description.

pub struct ComponentEntry {
    pub slug: &'static str,
    pub display_name: &'static str,
    pub description: &'static str,
}

pub static PRIMITIVES: &[ComponentEntry] = &[
    ComponentEntry { slug: "accordion", display_name: "Accordion", description: "Expandable disclosure panels." },
    ComponentEntry { slug: "alert-dialog", display_name: "AlertDialog", description: "Focused confirmation modal." },
    ComponentEntry { slug: "badge", display_name: "Badge", description: "Small status label." },
    ComponentEntry { slug: "banner", display_name: "Banner", description: "Persistent message bar." },
    ComponentEntry { slug: "box", display_name: "Box", description: "Generic layout container." },
    ComponentEntry { slug: "button", display_name: "Button", description: "Primary interactive control." },
    ComponentEntry { slug: "calendar", display_name: "Calendar", description: "Date grid for picking a single date." },
    ComponentEntry { slug: "callout", display_name: "Callout", description: "Highlighted informational block." },
    ComponentEntry { slug: "checkbox", display_name: "Checkbox", description: "Boolean toggle with label." },
    ComponentEntry { slug: "code", display_name: "Code", description: "Syntax-highlighted code display." },
    ComponentEntry { slug: "collapsible", display_name: "Collapsible", description: "Show/hide content toggle." },
    ComponentEntry { slug: "color-picker", display_name: "ColorPicker", description: "Color selection with swatches." },
    ComponentEntry { slug: "combobox", display_name: "Combobox", description: "Text input with dropdown." },
    ComponentEntry { slug: "context-menu", display_name: "ContextMenu", description: "Right-click triggered menu." },
    ComponentEntry { slug: "date-picker", display_name: "DatePicker", description: "Date selection with calendar." },
    ComponentEntry { slug: "date-range-picker", display_name: "DateRangePicker", description: "Dual calendar date range." },
    ComponentEntry { slug: "date-time-picker", display_name: "DateTimePicker", description: "Combined date and time." },
    ComponentEntry { slug: "date-time-range-picker", display_name: "DateTimeRangePicker", description: "Date-time range selection." },
    ComponentEntry { slug: "dialog", display_name: "Dialog", description: "Modal overlay." },
    ComponentEntry { slug: "drawer", display_name: "Drawer", description: "Slide-out panel from edge." },
    ComponentEntry { slug: "duration-input", display_name: "DurationInput", description: "Segmented duration entry." },
    ComponentEntry { slug: "editable-label", display_name: "EditableLabel", description: "Inline editable text." },
    ComponentEntry { slug: "eyebrow", display_name: "Eyebrow", description: "Small uppercase label." },
    ComponentEntry { slug: "field", display_name: "Field", description: "Form field wrapper." },
    ComponentEntry { slug: "file-upload", display_name: "FileUpload", description: "File input with drag-and-drop." },
    ComponentEntry { slug: "form-actions", display_name: "FormActions", description: "Action row for forms." },
    ComponentEntry { slug: "grid", display_name: "Grid", description: "CSS Grid layout container." },
    ComponentEntry { slug: "hover-card", display_name: "HoverCard", description: "Rich preview on hover." },
    ComponentEntry { slug: "icon", display_name: "Icon", description: "SVG icon from registry." },
    ComponentEntry { slug: "icon-button", display_name: "IconButton", description: "Icon-only button." },
    ComponentEntry { slug: "inline", display_name: "Inline", description: "Horizontal flex layout." },
    ComponentEntry { slug: "menu", display_name: "Menu", description: "Dropdown menu." },
    ComponentEntry { slug: "menubar", display_name: "Menubar", description: "Horizontal menu bar." },
    ComponentEntry { slug: "meter", display_name: "Meter", description: "Visual gauge for values." },
    ComponentEntry { slug: "navigation-menu", display_name: "NavigationMenu", description: "Navigation with dropdowns." },
    ComponentEntry { slug: "number-entry", display_name: "NumberEntry", description: "Numeric input with controls." },
    ComponentEntry { slug: "pagination", display_name: "Pagination", description: "Page navigation controls." },
    ComponentEntry { slug: "pill", display_name: "Pill", description: "Small inline label chip." },
    ComponentEntry { slug: "pin-input", display_name: "PinInput", description: "Multi-digit code entry." },
    ComponentEntry { slug: "popover", display_name: "Popover", description: "Anchored overlay." },
    ComponentEntry { slug: "progress", display_name: "Progress", description: "Progress indicator." },
    ComponentEntry { slug: "radio-group", display_name: "RadioGroup", description: "Single-selection group." },
    ComponentEntry { slug: "range-calendar", display_name: "RangeCalendar", description: "Calendar for date ranges." },
    ComponentEntry { slug: "range-slider", display_name: "RangeSlider", description: "Dual-thumb slider." },
    ComponentEntry { slug: "rating", display_name: "Rating", description: "Star-based rating." },
    ComponentEntry { slug: "scroll-shell", display_name: "ScrollShell", description: "Scrollable container." },
    ComponentEntry { slug: "search-field", display_name: "SearchField", description: "Search text input." },
    ComponentEntry { slug: "segmented-control", display_name: "SegmentedControl", description: "Inline toggle options." },
    ComponentEntry { slug: "select", display_name: "Select", description: "Dropdown selection." },
    ComponentEntry { slug: "separator", display_name: "Separator", description: "Visual divider." },
    ComponentEntry { slug: "skeleton", display_name: "Skeleton", description: "Placeholder loading shape." },
    ComponentEntry { slug: "slider", display_name: "Slider", description: "Single-thumb slider." },
    ComponentEntry { slug: "spacer", display_name: "Spacer", description: "Flexible space." },
    ComponentEntry { slug: "split-button", display_name: "SplitButton", description: "Button with dropdown." },
    ComponentEntry { slug: "stack", display_name: "Stack", description: "Vertical flex layout." },
    ComponentEntry { slug: "status-indicator", display_name: "StatusIndicator", description: "Colored status dot." },
    ComponentEntry { slug: "surface", display_name: "Surface", description: "Themed container." },
    ComponentEntry { slug: "switch", display_name: "Switch", description: "Toggle switch." },
    ComponentEntry { slug: "table", display_name: "Table", description: "Static data table." },
    ComponentEntry { slug: "tabs", display_name: "Tabs", description: "Tabbed interface." },
    ComponentEntry { slug: "text-area", display_name: "TextArea", description: "Multi-line text input." },
    ComponentEntry { slug: "text-input", display_name: "TextInput", description: "Single-line text input." },
    ComponentEntry { slug: "time-ago", display_name: "TimeAgo", description: "Relative timestamp." },
    ComponentEntry { slug: "time-field", display_name: "TimeField", description: "Time-of-day input." },
    ComponentEntry { slug: "time-zone-select", display_name: "TimeZoneSelect", description: "Timezone selection." },
    ComponentEntry { slug: "toggle", display_name: "Toggle", description: "Pressable toggle button." },
    ComponentEntry { slug: "toggle-group", display_name: "ToggleGroup", description: "Mutually exclusive toggles." },
    ComponentEntry { slug: "toolbar", display_name: "Toolbar", description: "Horizontal action bar." },
    ComponentEntry { slug: "tooltip", display_name: "Tooltip", description: "Informational overlay." },
    ComponentEntry { slug: "tri-state-switch", display_name: "TriStateSwitch", description: "Three-position switch." },
    ComponentEntry { slug: "zoned-date-time-picker", display_name: "ZonedDateTimePicker", description: "Date-time with timezone." },
];

pub static COMPOSITES: &[ComponentEntry] = &[
    ComponentEntry { slug: "audio-player", display_name: "AudioPlayer", description: "Audio playback controls." },
    ComponentEntry { slug: "autonomous-list", display_name: "AutonomousList", description: "Self-managing list." },
    ComponentEntry { slug: "block-editor", display_name: "BlockEditor", description: "Block-based content editor." },
    ComponentEntry { slug: "breadcrumbs", display_name: "Breadcrumbs", description: "Navigation trail." },
    ComponentEntry { slug: "bulk-action-bar", display_name: "BulkActionBar", description: "Batch action bar." },
    ComponentEntry { slug: "card", display_name: "Card", description: "Contained surface for content." },
    ComponentEntry { slug: "card-radio-group", display_name: "CardRadioGroup", description: "Radio selection across cards." },
    ComponentEntry { slug: "confirm-action", display_name: "ConfirmAction", description: "Confirmation before action." },
    ComponentEntry { slug: "data-table", display_name: "DataTable", description: "Feature-rich table." },
    ComponentEntry { slug: "detail-row", display_name: "DetailRow", description: "Label-value metadata pair." },
    ComponentEntry { slug: "detail-section", display_name: "DetailSection", description: "Titled detail section." },
    ComponentEntry { slug: "detail-shell", display_name: "DetailShell", description: "Full detail page layout." },
    ComponentEntry { slug: "embed-input", display_name: "EmbedInput", description: "URL or embed code input." },
    ComponentEntry { slug: "embed-preview", display_name: "EmbedPreview", description: "Rich preview for embeds." },
    ComponentEntry { slug: "embed-shell", display_name: "EmbedShell", description: "Container for external content." },
    ComponentEntry { slug: "empty-state", display_name: "EmptyState", description: "Placeholder for empty views." },
    ComponentEntry { slug: "filter-toolbar", display_name: "FilterToolbar", description: "Filter controls toolbar." },
    ComponentEntry { slug: "form-dialog", display_name: "FormDialog", description: "Modal dialog with form." },
    ComponentEntry { slug: "grid-shell", display_name: "GridShell", description: "Grid layout browse view." },
    ComponentEntry { slug: "inline-editable-field", display_name: "InlineEditableField", description: "Click-to-edit text field." },
    ComponentEntry { slug: "list-card", display_name: "ListCard", description: "Structured list item card." },
    ComponentEntry { slug: "list-shell", display_name: "ListShell", description: "List layout browse view." },
    ComponentEntry { slug: "log-list", display_name: "LogList", description: "Timestamped log viewer." },
    ComponentEntry { slug: "markdown-editor", display_name: "MarkdownEditor", description: "Markdown authoring with preview." },
    ComponentEntry { slug: "media-picker", display_name: "MediaPicker", description: "Media asset selection dialog." },
    ComponentEntry { slug: "media-preview", display_name: "MediaPreview", description: "Media asset preview." },
    ComponentEntry { slug: "media-thumbnail", display_name: "MediaThumbnail", description: "Compact media thumbnail." },
    ComponentEntry { slug: "nav-card", display_name: "NavCard", description: "Navigation-oriented card." },
    ComponentEntry { slug: "nav-card-grid", display_name: "NavCardGrid", description: "Responsive NavCard grid." },
    ComponentEntry { slug: "order-by", display_name: "OrderBy", description: "Sort-control toolbar." },
    ComponentEntry { slug: "page-header", display_name: "PageHeader", description: "Page-level header." },
    ComponentEntry { slug: "page-loading", display_name: "PageLoading", description: "Full-viewport loading overlay." },
    ComponentEntry { slug: "pagination-summary", display_name: "PaginationSummary", description: "Pagination state summary." },
    ComponentEntry { slug: "picker-shell", display_name: "PickerShell", description: "Search-and-select picker." },
    ComponentEntry { slug: "relation-picker", display_name: "RelationPicker", description: "Searchable related items picker." },
    ComponentEntry { slug: "reorderable-list", display_name: "ReorderableList", description: "Drag-and-drop list." },
    ComponentEntry { slug: "selection-summary", display_name: "SelectionSummary", description: "Current selection state." },
    ComponentEntry { slug: "slug-field", display_name: "SlugField", description: "URL-safe slug field." },
    ComponentEntry { slug: "state-tile", display_name: "StateTile", description: "Compact label-value tile." },
    ComponentEntry { slug: "toast-stack", display_name: "ToastStack", description: "Stacked notification manager." },
    ComponentEntry { slug: "video-player", display_name: "VideoPlayer", description: "Video playback controls." },
];
