import { createRequire } from "node:module";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";

type IconNodes = [string, Record<string, string>][];
type Manifest = {
  lucideVersion: string;
  icons: string[];
  aliases: Record<string, string>;
};

const checkOnly = process.argv.includes("--check");
const repoRoot = resolve(import.meta.dir, "..");
const manifestPath = join(
  repoRoot,
  "packages/core/src/icons/default-icons.json",
);
const tsRoot = join(repoRoot, "packages/core/src/icons");
const moduleRoot = join(tsRoot, "icons");
const svgRoot = join(repoRoot, "packages/render/assets/icons");
const legacySvgRoot = join(repoRoot, "packages/gpui/preview/assets/icons");
const requireFromRoot = createRequire(join(repoRoot, "package.json"));
const cataloguePath = requireFromRoot.resolve("lucide-static/icon-nodes.json");
const lucidePackagePath = requireFromRoot.resolve("lucide-static/package.json");

const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Manifest;
const lucidePackage = JSON.parse(readFileSync(lucidePackagePath, "utf8")) as {
  version: string;
};
const catalogue = JSON.parse(readFileSync(cataloguePath, "utf8")) as Record<
  string,
  IconNodes
>;

if (lucidePackage.version !== manifest.lucideVersion) {
  throw new Error(
    `Default icons require lucide-static ${manifest.lucideVersion}; resolved ${lucidePackage.version}.`,
  );
}

const canonicalNames = [...manifest.icons];
const aliasNames = Object.keys(manifest.aliases);
const supportedNames = [...canonicalNames, ...aliasNames].sort();
if (new Set(supportedNames).size !== supportedNames.length) {
  throw new Error("Default icon names and aliases must be unique.");
}
if (canonicalNames.join("\n") !== [...canonicalNames].sort().join("\n")) {
  throw new Error("Canonical default icon names must be sorted.");
}
if (aliasNames.join("\n") !== [...aliasNames].sort().join("\n")) {
  throw new Error("Default icon aliases must be sorted.");
}

for (const [alias, target] of Object.entries(manifest.aliases)) {
  if (!canonicalNames.includes(target)) {
    throw new Error(`Alias ${alias} targets missing canonical icon ${target}.`);
  }
}
for (const name of canonicalNames) {
  if (!catalogue[name]) throw new Error(`Lucide has no icon named ${name}.`);
}

const reserved = new Set([
  "delete",
  "export",
  "import",
  "package",
  "private",
  "public",
  "static",
]);
function exportName(name: string): string {
  const candidate = name.replace(/-([a-z0-9])/g, (_, character: string) =>
    character.toUpperCase(),
  );
  return reserved.has(candidate) ? `${candidate}Icon` : candidate;
}

function nodesFor(name: string): IconNodes {
  return catalogue[manifest.aliases[name] ?? name];
}

function renderModule(name: string): string {
  return [
    "// Generated by scripts/build-default-icons.ts. Do not edit.",
    'import type { IconNodes } from "../types";',
    "",
    `export const ${exportName(name)}: IconNodes = ${JSON.stringify(nodesFor(name))};`,
    "",
  ].join("\n");
}

function renderIndex(): string {
  const imports = supportedNames.map(
    (name) => `import { ${exportName(name)} } from "./icons/${name}";`,
  );
  const exports = supportedNames.map((name) => `  ${exportName(name)},`);
  const entries = supportedNames.map(
    (name) => `  ${JSON.stringify(name)}: ${exportName(name)},`,
  );
  return [
    "// Generated by scripts/build-default-icons.ts. Do not edit.",
    ...imports,
    'import type { IconSet } from "./types";',
    "",
    "export {",
    ...exports,
    "};",
    "",
    "/** Poodle-owned Lucide names available without operator wiring. */",
    "export const defaultLucideIconSet: IconSet = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

function renderAliases(): string {
  return [
    "// Generated by scripts/build-default-icons.ts. Do not edit.",
    "/** Legacy and shorthand names mapped to canonical Lucide names. */",
    `export const iconAliases: Readonly<Record<string, string>> = ${JSON.stringify(manifest.aliases, null, 2)};`,
    "",
  ].join("\n");
}



function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function renderSvg(name: string): string {
  const children = nodesFor(name)
    .map(([tag, attributes]) => {
      const props = Object.entries(attributes)
        .map(([key, value]) => `${key}="${escapeXml(value)}"`)
        .join(" ");
      return `<${tag}${props ? ` ${props}` : ""}/>`;
    })
    .join("");
  return [
    `<!-- @license lucide-static v${manifest.lucideVersion} - ISC -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${children}</svg>`,
    "",
  ].join("\n");
}

const expected = new Map<string, string>();
for (const name of supportedNames) {
  expected.set(join(moduleRoot, `${name}.ts`), renderModule(name));
  expected.set(join(svgRoot, `${name}.svg`), renderSvg(name));
}
expected.set(join(tsRoot, "generated.ts"), renderIndex());
expected.set(join(tsRoot, "aliases.generated.ts"), renderAliases());

function generatedFiles(root: string, extension: string): string[] {
  if (!existsSync(root)) return [];
  return readdirSync(root)
    .filter((name) => name.endsWith(extension))
    .map((name) => join(root, name));
}

const actualModules = generatedFiles(moduleRoot, ".ts");
const actualSvgs = generatedFiles(svgRoot, ".svg");
const legacySvgs = generatedFiles(legacySvgRoot, ".svg");
const stale = [...actualModules, ...actualSvgs, ...legacySvgs].filter(
  (path) => !expected.has(path),
);
const drift = [...expected].filter(([path, content]) => {
  try {
    return readFileSync(path, "utf8") !== content;
  } catch {
    return true;
  }
});

if (checkOnly) {
  if (stale.length > 0 || drift.length > 0) {
    const paths = [...stale, ...drift.map(([path]) => path)]
      .map((path) => path.replace(`${repoRoot}/`, ""))
      .sort();
    throw new Error(`Default icon artifacts are stale:\n${paths.join("\n")}`);
  }
} else {
  mkdirSync(moduleRoot, { recursive: true });
  mkdirSync(svgRoot, { recursive: true });
  for (const path of stale) unlinkSync(path);
  for (const [path, content] of expected) writeFileSync(path, content);
}

console.log(
  `${checkOnly ? "Verified" : "Generated"} ${supportedNames.length} default icon names (${canonicalNames.length} canonical, ${aliasNames.length} aliases) from lucide-static ${manifest.lucideVersion}.`,
);
