//! The single Rust component implementation.
//!
//! Each component here is a pure function `Spec + Theme → poodle_node::Node`.
//! No backend types, no measurement, no window: what a Button *is*, decided
//! once. Per-backend adapters (GPUI's in this repo, Jetstream's in its own)
//! interpret the node tree; the parity evidence for each backend lives with
//! that backend, against fixtures this crate can generate headlessly.
//!
//! Started 2026-08-04 with `Select` — deliberately the hardest component
//! (overlay anchoring, filtering, groups, a trigger with nested clickables) —
//! so the vocabulary was proven where it was most likely to fail. The rest of
//! the tier migrates component-by-component; each port deletes its
//! `packages/jetstream/components` and `packages/gpui/components`
//! predecessors once its parity fixtures are green on both backends.

pub mod avatar;
pub mod accordion;
pub mod action_discovery_panel;
pub mod agent_chat_input;
pub mod agent_message;
pub mod agent_question;
pub mod agent_question_record;
pub mod agent_transcript;
pub mod alert_dialog;
pub mod badge;
pub mod banner;
pub mod block_editor;
pub mod breadcrumbs;
pub mod button;
pub mod callout;
pub mod card;
pub mod checkbox;
pub mod code;
pub mod code_input;
pub mod collapse_toggle;
pub mod collapsible;
pub mod color;
pub mod color_picker;
pub mod context_menu;
pub mod detail_item;
pub mod dialog;
pub mod dock_region;
pub mod drawer;
pub mod empty_state;
pub mod error_boundary;
pub mod floating_overlay;
pub mod eyebrow;
pub mod field;
pub mod file_upload;
pub mod field_set;
pub mod icon;
pub mod menu;
pub mod menubar;
pub mod meta_bar;
pub mod meta_item;
pub mod icon_button;
pub mod app_header;
pub mod audio_player;
pub mod bulk_action_bar;
pub mod calendar;
pub mod card_radio_group;
pub mod card_toggle_group;
pub mod changed_files;
pub mod command_palette;
pub mod confirm_action;
pub mod data_table;
pub mod date_picker;
pub mod date_range_picker;
pub mod date_time_picker;
pub mod date_time_range_picker;
pub mod date_time_zone_picker;
pub mod debug_dialog;
pub mod detail_section;
pub mod detail_section_group;
pub mod detail_shell;
pub mod duration_input;
pub mod editable_label;
pub mod editable_list;
pub mod embed_input;
pub mod embed_preview;
pub mod filter_builder;
pub mod filter_toolbar;
pub mod form_actions;
pub mod form_dialog;
pub mod form_layout;
pub mod form_shell;
pub mod grid;
pub mod hover_card;
pub mod inline_list_section;
pub mod inline_remediation;
pub mod list_card;
pub mod list_card_counter;
pub mod list_container;
pub mod list_grid;
pub mod log_list;
pub mod markdown_editor;
pub mod media_browse_panel;
pub mod media_picker;
pub mod media_preview;
pub mod media_thumbnail;
pub mod meter;
pub mod metric_tile;
pub mod model_picker;
pub mod nav_card;
pub mod navigation_menu;
pub mod number_input;
pub mod order_by;
pub mod page_header;
pub mod page_loading;
pub mod pagination;
pub mod pagination_summary;
pub mod password_requirements;
pub mod picker_shell;
pub mod pill;
pub mod popover;
pub mod presentation;
pub mod progress;
pub mod radio_group;
pub mod range_slider;
pub mod rating;
pub mod ref_select;
pub mod region;
pub mod relation_picker;
pub mod remediation_banner;
pub mod resize_handle;
pub mod scroll_shell;
pub mod segmented_control;
pub mod select;
pub mod selection_summary;
pub mod separator;
pub mod shell_status_bar;
pub mod sidebar_nav;
pub mod skeleton;
pub mod spacer;
pub mod slider;
pub mod spinner;
pub mod split_button;
pub mod split_view;
pub mod stack;
pub mod state_tile;
pub mod status_indicator;
pub mod stepper;
pub mod surface;
pub mod switch;
pub mod tab_strip;
pub mod table;
pub mod tabs;
pub mod text;
pub mod text_input;
pub mod time_field;
pub mod time_zone_select;
pub mod toolbar;
pub mod text_link;
pub mod theme_select;
pub mod time_ago;
pub mod toast_host;
pub mod toast_stack;
pub mod toggle_group;
pub mod token_input;
pub mod tool_call;
pub mod tool_call_group;
pub mod tooltip;
pub mod tree;
pub mod tri_state_switch;
pub mod validation_summary;
pub mod video_player;

pub use avatar::avatar;
pub use accordion::accordion;
pub use action_discovery_panel::action_discovery_panel;
pub use agent_chat_input::{agent_chat_input, AgentChatInputHandlers};
pub use agent_message::agent_message;
pub use agent_question::{agent_question, AgentQuestionHandlers};
pub use agent_question_record::agent_question_record;
pub use agent_transcript::{agent_transcript, AgentTranscriptHandlers};
pub use alert_dialog::{alert_dialog, AlertDialogHandlers, DEFAULT_WORKING_LABEL};
pub use badge::badge;
pub use banner::banner;
pub use block_editor::block_editor;
pub use breadcrumbs::breadcrumbs;
pub use button::button;
pub use callout::callout;
pub use card::card;
pub use checkbox::checkbox;
pub use code::code;
pub use code_input::code_input;
pub use collapse_toggle::collapse_toggle;
pub use collapsible::collapsible;
pub use color_picker::{color_picker, ColorPickerHandlers};
pub use context_menu::context_menu;
pub use detail_item::{detail_item, detail_item_with_slots};
pub use dialog::dialog;
pub use dock_region::{dock_region, DockRegionHandlers};
pub use drawer::drawer;
pub use empty_state::empty_state;
pub use error_boundary::error_boundary;
pub use floating_overlay::floating_overlay;
pub use eyebrow::eyebrow;
pub use field::field;
pub use file_upload::file_upload;
pub use field_set::field_set;
pub use icon::icon;
pub use menu::menu;
pub use menubar::menubar;
pub use meta_bar::{meta_bar, meta_bar_sep};
pub use meta_item::meta_item;
pub use icon_button::icon_button;
pub use app_header::app_header;
pub use audio_player::audio_player;
pub use bulk_action_bar::{bulk_action_bar, BulkActionBarHandlers};
pub use calendar::{calendar, CalendarHandlers};
pub use card_radio_group::card_radio_group;
pub use card_toggle_group::card_toggle_group;
pub use changed_files::{changed_files, ChangedFilesHandlers};
pub use command_palette::command_palette;
pub use confirm_action::{confirm_action, ConfirmActionHandlers};
pub use data_table::{data_table, data_table_loading, DataTableHandlers};
pub use date_picker::{date_picker, DatePickerHandlers};
pub use date_range_picker::date_range_picker;
pub use date_time_picker::date_time_picker;
pub use date_time_range_picker::date_time_range_picker;
pub use date_time_zone_picker::{date_time_zone_picker, DateTimeZonePickerHandlers};
pub use debug_dialog::debug_dialog;
pub use detail_section::detail_section;
pub use duration_input::duration_input;
pub use detail_section_group::detail_section_group;
pub use detail_shell::detail_shell;
pub use editable_label::editable_label;
pub use editable_list::{editable_list, EditableListHandlers};
pub use embed_input::embed_input;
pub use embed_preview::embed_preview;
pub use filter_builder::{filter_builder, FilterBuilderHandlers};
pub use filter_toolbar::filter_toolbar;
pub use form_actions::{form_actions, form_actions_full};
pub use form_dialog::{form_dialog, FormDialogHandlers};
pub use form_layout::form_layout;
pub use form_shell::form_shell;
pub use grid::grid;
pub use hover_card::hover_card;
pub use inline_list_section::inline_list_section;
pub use inline_remediation::inline_remediation;
pub use list_card::{list_card, ListCardSlots};
pub use list_card_counter::list_card_counter;
pub use list_container::{list_container, ListContainerSlots};
pub use list_grid::list_grid;
pub use log_list::log_list;
pub use markdown_editor::markdown_editor;
pub use media_browse_panel::media_browse_panel;
pub use media_picker::{media_picker, MediaPickerHandlers};
pub use media_preview::media_preview;
pub use media_thumbnail::media_thumbnail;
pub use meter::meter;
pub use metric_tile::metric_tile;
pub use model_picker::model_picker;
pub use nav_card::nav_card;
pub use navigation_menu::navigation_menu;
pub use number_input::{number_input, NumberInputHandlers};
pub use order_by::{order_by, OrderByHandlers};
pub use page_header::page_header;
pub use page_loading::page_loading;
pub use pagination::pagination;
pub use pagination_summary::pagination_summary;
pub use password_requirements::password_requirements;
pub use picker_shell::picker_shell;
pub use pill::pill;
pub use popover::popover;
pub use progress::progress;
pub use radio_group::radio_group;
pub use range_slider::{range_slider, RangeSliderHandlers};
pub use rating::rating;
pub use ref_select::ref_select;
pub use region::region;
pub use relation_picker::{relation_picker, RelationPickerHandlers};
pub use remediation_banner::remediation_banner;
pub use resize_handle::{resize_handle, ResizePhase};
pub use scroll_shell::scroll_shell;
pub use segmented_control::segmented_control;
pub use select::{select, SelectHandlers};
pub use selection_summary::{selection_summary, SelectionSummaryHandlers};
pub use separator::separator;
pub use shell_status_bar::shell_status_bar;
pub use sidebar_nav::sidebar_nav;
pub use skeleton::skeleton;
pub use spacer::spacer;
pub use slider::{slider, SliderHandlers};
pub use spinner::spinner;
pub use split_button::{split_button, SplitButtonHandlers};
pub use split_view::{split_view, SplitViewHandlers};
pub use stack::stack;
pub use state_tile::state_tile;
pub use status_indicator::status_indicator;
pub use stepper::{stepper, StepperHandlers};
pub use surface::surface;
pub use switch::switch;
pub use tab_strip::{tab_strip, TabStripHandlers};
pub use table::table;
pub use tabs::{tabs, TabHandler};
pub use text::text;
pub use toolbar::toolbar;
pub use text_input::text_input;
pub use time_field::time_field;
pub use time_zone_select::{time_zone_select, TimeZoneSelectHandlers};
pub use text_link::text_link;
pub use theme_select::theme_select;
pub use time_ago::time_ago;
pub use toast_host::toast_host;
pub use toast_stack::{toast_stack, ToastStackHandlers};
pub use toggle_group::toggle_group;
pub use token_input::token_input;
pub use tool_call::tool_call;
pub use tool_call_group::{tool_call_group, ToolCallGroupHandlers};
pub use tooltip::tooltip;
pub use tree::{tree, TreeHandlers};
pub use tri_state_switch::tri_state_switch;
pub use validation_summary::validation_summary;
pub use video_player::video_player;
