//! The single Rust component implementation.
//!
//! Each component here is a pure function `Spec + Theme → poodle_node::Node`.
//! No backend types, no measurement, no window: what a Button *is*, decided
//! once. Per-backend adapters (GPUI's in this repo, Jetstream's in its own)
//! interpret the node tree; the parity evidence for each backend lives with
//! that backend, against fixtures this crate can generate headlessly.
//!
//! Started 2026-08-04 with `Select` — deliberately the hardest component
//! (overlay anchoring, filtering, groups, a trigger with nested clickables) —
//! so the vocabulary was proven where it was most likely to fail. The rest of
//! the tier migrates component-by-component; each port deletes its
//! `packages/jetstream/components` and `packages/gpui/components`
//! predecessors once its parity fixtures are green on both backends.

pub mod avatar;
pub mod accordion;
pub mod alert_dialog;
pub mod badge;
pub mod banner;
pub mod breadcrumbs;
pub mod button;
pub mod callout;
pub mod card;
pub mod checkbox;
pub mod code;
pub mod collapse_toggle;
pub mod collapsible;
pub mod color;
pub mod context_menu;
pub mod detail_item;
pub mod dialog;
pub mod drawer;
pub mod empty_state;
pub mod error_boundary;
pub mod floating_overlay;
pub mod eyebrow;
pub mod field;
pub mod file_upload;
pub mod field_set;
pub mod icon;
pub mod menu;
pub mod menubar;
pub mod meta_bar;
pub mod meta_item;
pub mod icon_button;
pub mod app_header;
pub mod bulk_action_bar;
pub mod calendar;
pub mod command_palette;
pub mod confirm_action;
pub mod data_table;
pub mod date_picker;
pub mod date_range_picker;
pub mod date_time_picker;
pub mod date_time_range_picker;
pub mod date_time_zone_picker;
pub mod debug_dialog;
pub mod detail_section;
pub mod detail_section_group;
pub mod detail_shell;
pub mod duration_input;
pub mod editable_label;
pub mod editable_list;
pub mod grid;
pub mod list_card_counter;
pub mod list_container;
pub mod list_grid;
pub mod page_header;
pub mod pagination;
pub mod pagination_summary;
pub mod pill;
pub mod presentation;
pub mod progress;
pub mod radio_group;
pub mod region;
pub mod scroll_shell;
pub mod segmented_control;
pub mod select;
pub mod separator;
pub mod skeleton;
pub mod spacer;
pub mod slider;
pub mod spinner;
pub mod stack;
pub mod surface;
pub mod switch;
pub mod tabs;
pub mod text;
pub mod text_input;
pub mod time_field;
pub mod time_zone_select;
pub mod toolbar;
pub mod text_link;
pub mod tooltip;

pub use avatar::avatar;
pub use accordion::accordion;
pub use alert_dialog::{alert_dialog, AlertDialogHandlers, DEFAULT_WORKING_LABEL};
pub use badge::badge;
pub use banner::banner;
pub use breadcrumbs::breadcrumbs;
pub use button::button;
pub use callout::callout;
pub use card::card;
pub use checkbox::checkbox;
pub use code::code;
pub use collapse_toggle::collapse_toggle;
pub use collapsible::collapsible;
pub use context_menu::context_menu;
pub use detail_item::{detail_item, detail_item_with_slots};
pub use dialog::dialog;
pub use drawer::drawer;
pub use empty_state::empty_state;
pub use error_boundary::error_boundary;
pub use floating_overlay::floating_overlay;
pub use eyebrow::eyebrow;
pub use field::field;
pub use file_upload::file_upload;
pub use field_set::field_set;
pub use icon::icon;
pub use menu::menu;
pub use menubar::menubar;
pub use meta_bar::{meta_bar, meta_bar_sep};
pub use meta_item::meta_item;
pub use icon_button::icon_button;
pub use app_header::app_header;
pub use bulk_action_bar::{bulk_action_bar, BulkActionBarHandlers};
pub use calendar::{calendar, CalendarHandlers};
pub use command_palette::command_palette;
pub use confirm_action::{confirm_action, ConfirmActionHandlers};
pub use data_table::{data_table, data_table_loading, DataTableHandlers};
pub use date_picker::{date_picker, DatePickerHandlers};
pub use date_range_picker::date_range_picker;
pub use date_time_picker::date_time_picker;
pub use date_time_range_picker::date_time_range_picker;
pub use date_time_zone_picker::{date_time_zone_picker, DateTimeZonePickerHandlers};
pub use debug_dialog::debug_dialog;
pub use detail_section::detail_section;
pub use duration_input::duration_input;
pub use detail_section_group::detail_section_group;
pub use detail_shell::detail_shell;
pub use editable_label::editable_label;
pub use editable_list::{editable_list, EditableListHandlers};
pub use grid::grid;
pub use list_card_counter::list_card_counter;
pub use list_container::{list_container, ListContainerSlots};
pub use list_grid::list_grid;
pub use page_header::page_header;
pub use pagination::pagination;
pub use pagination_summary::pagination_summary;
pub use pill::pill;
pub use progress::progress;
pub use radio_group::radio_group;
pub use region::region;
pub use scroll_shell::scroll_shell;
pub use segmented_control::segmented_control;
pub use select::{select, SelectHandlers};
pub use separator::separator;
pub use skeleton::skeleton;
pub use spacer::spacer;
pub use slider::{slider, SliderHandlers};
pub use spinner::spinner;
pub use stack::stack;
pub use surface::surface;
pub use switch::switch;
pub use tabs::{tabs, TabHandler};
pub use text::text;
pub use toolbar::toolbar;
pub use text_input::text_input;
pub use time_field::time_field;
pub use time_zone_select::{time_zone_select, TimeZoneSelectHandlers};
pub use text_link::text_link;
pub use tooltip::tooltip;
